"""
tests/test_urs_generation_job.py — Regression tests for background URS AI
generation (services/urs_generation_job.py).

Root cause under test: routes/urs.py's /generate endpoint used to iterate
generate_content_stream() *inside* the Flask request, holding a gunicorn
worker for the whole generation time. On large section selections this
exceeded Render's `--timeout=60` and the worker was SIGKILLed mid-stream
([CRITICAL] WORKER TIMEOUT). These tests assert the new behavior instead:
submit_generation_job() returns immediately no matter how long the AI call
takes, progress/results are visible by polling SQLite, one bad batch never
loses requirements already generated by other batches, and — per a
follow-up hardening pass — malformed/truncated output is retried and
salvaged rather than failing the batch outright, while genuine API errors
and safety blocks are never retried at this layer.

Stage 2 (AI Gateway migration): _generate_batch() now calls
pharmagpt.providers.router.generate_content(TaskIntent.URS, ...) instead of
a module-level gemini_client, so these tests inject fake provider responses
by registering fake providers with the router (isolated per test — see
isolated_gateway below) instead of monkeypatching gen_job.gemini_client
directly. Every test that registers a "gemini" fake also registers (or
explicitly refuses) a "nemotron" fake, since the gateway will now try the
opposite provider on a fallback-eligible failure — this keeps each test's
outcome deterministic regardless of whether a real NVIDIA_API_KEY happens
to be set in the environment running the suite.
"""

import json
import time

import pytest
from google.genai import errors as genai_errors

from pharmagpt import urs_database as udb
from pharmagpt.providers import router as ai_router
from pharmagpt.services import urs_generation_job as gen_job
from google.genai import types


class _FakeModels:
    def __init__(self, fn):
        self._fn = fn

    def generate_content(self, *, model=None, contents=None, config=None):
        return self._fn(contents, config)


class _FakeClient:
    def __init__(self, fn):
        self.models = _FakeModels(fn)


class _FakeUsage:
    def __init__(self, prompt_tokens=100, response_tokens=200):
        self.prompt_token_count = prompt_tokens
        self.candidates_token_count = response_tokens


class _FakeCandidate:
    def __init__(self, finish_reason=types.FinishReason.STOP):
        self.finish_reason = finish_reason


class _FakeResponse:
    def __init__(self, text, prompt_tokens=100, response_tokens=200, finish_reason=types.FinishReason.STOP):
        self.text = text
        self.usage_metadata = _FakeUsage(prompt_tokens, response_tokens)
        self.candidates = [_FakeCandidate(finish_reason)]


@pytest.fixture()
def isolated_gateway(isolated_ai_gateway, monkeypatch):
    """conftest.py's isolated_ai_gateway plus the specific provider defaults
    this file's tests rely on, explicit rather than ambient — matches
    tests/test_provider_router.py's own isolated_router convention of
    pinning DEFAULT_CHAT_PROVIDER/DEFAULT_DOCUMENT_PROVIDER/ENABLE_FALLBACK
    rather than depending on whatever pharmagpt/config.py currently
    defaults to."""
    monkeypatch.setattr(isolated_ai_gateway, "DEFAULT_DOCUMENT_PROVIDER", "gemini")
    monkeypatch.setattr(isolated_ai_gateway, "ENABLE_FALLBACK", True)
    return isolated_ai_gateway


def _register(rt, name, fn, model="fake-model"):
    """Register a fake provider under `name`; fn(contents, config) plays
    the role of that provider's response (return a _FakeResponse) or
    failure (raise) for one call."""
    rt.register_provider(name, lambda: _FakeClient(fn), model=model)


def _refuse(name):
    """A fake provider that must never be called — registering this proves
    a happy-path (or already-classified-non-fallback-eligible) call never
    triggers a fallback attempt it doesn't need."""
    def _fn(contents, config):
        raise AssertionError(f"{name} should not have been called")
    return _fn


def _make_urs():
    return udb.create_urs({
        "title": "URS - Autoclave", "equipment_name": "Autoclave-01",
        "equipment_type": "Autoclave", "category": "Equipment",
    }, company_id="test-company-1")


def _req_json(section):
    return json.dumps([{
        "section": section, "requirement": "The system shall do X.",
        "rationale": "GMP", "priority": "High", "gmp_criticality": "GMP-Critical",
        "regulatory_ref": "21 CFR Part 11", "verification_method": "Functional Test",
        "acceptance_criteria": "Pass/fail",
    }])


def _wait_for_terminal_generation(urs_id, timeout=10.0):
    deadline = time.monotonic() + timeout
    status = None
    while time.monotonic() < deadline:
        status = udb.get_generation_status(urs_id)
        if status["generation_status"] in ("completed", "failed"):
            return status
        time.sleep(0.05)
    pytest.fail(f"generation job never reached a terminal status: {status}")


def test_submit_generation_job_returns_immediately_and_completes_in_background(db_path, isolated_gateway):
    urs = _make_urs()

    def fake_generate_content(contents, config):
        time.sleep(0.05)  # simulated network latency, kept small for test speed
        return _FakeResponse(_req_json("Functional Requirements"))

    _register(isolated_gateway, "gemini", fake_generate_content)
    _register(isolated_gateway, "nemotron", _refuse("nemotron"))  # happy path never falls back

    start = time.monotonic()
    gen_job.submit_generation_job(urs["id"], urs, ["Functional Requirements", "Safety Requirements"])
    submit_elapsed = time.monotonic() - start

    # The whole point of this redesign: submitting must not block on the AI call.
    assert submit_elapsed < 0.5

    # Default URS_GENERATION_BATCH_SIZE (2) puts both sections in one batch.
    status = udb.get_generation_status(urs["id"])
    assert status["generation_status"] == "running"
    assert status["generation_progress_total"] == 1

    final = _wait_for_terminal_generation(urs["id"])
    assert final["generation_status"] == "completed"
    assert final["generation_result_count"] == 1

    saved = udb.get_requirements(urs["id"])
    assert len(saved) == 1
    assert saved[0]["section"] == "Functional Requirements"
    assert saved[0]["req_id"]  # numbered by section prefix

    # The fake only ever returns "Functional Requirements" content, so
    # section-coverage tracking should correctly report Safety as missing
    # even though the batch itself didn't raise.
    assert final["generation_message"] == (
        "1 of 2 sections generated successfully (1 requirements). "
        "1 section failed and can be retried: Safety Requirements."
    )


def test_run_generation_job_continues_after_one_batch_fails(db_path, isolated_gateway):
    urs = _make_urs()

    def fake_gemini(contents, config):
        prompt_text = contents[0].parts[0].text
        if "Safety Requirements" in prompt_text:
            raise genai_errors.ServerError(503, {"message": "backend unavailable", "status": "UNAVAILABLE"})
        return _FakeResponse(_req_json("Functional Requirements"))

    def fake_nemotron(contents, config):
        # Both providers genuinely down for the Safety batch — the gateway
        # is fully exhausted, not just Gemini, so that batch truly fails
        # end-to-end rather than silently succeeding via fallback.
        prompt_text = contents[0].parts[0].text
        if "Safety Requirements" in prompt_text:
            raise genai_errors.ServerError(503, {"message": "backend unavailable", "status": "UNAVAILABLE"})
        raise AssertionError("nemotron should not be called for the Functional Requirements batch")

    _register(isolated_gateway, "gemini", fake_gemini)
    _register(isolated_gateway, "nemotron", fake_nemotron)

    batches = [["Functional Requirements"], ["Safety Requirements"]]
    gen_job._run_generation_job(urs["id"], urs, batches)

    status = udb.get_generation_status(urs["id"])
    # One batch succeeded — the job is "completed" (failure surfaced via
    # generation_error / generation_message) rather than discarding the
    # partial result.
    assert status["generation_status"] == "completed"
    assert status["generation_result_count"] == 1
    assert "Batch 2" in status["generation_error"]
    assert status["generation_message"] == (
        "1 of 2 sections generated successfully (1 requirements). "
        "1 section failed and can be retried: Safety Requirements."
    )

    saved = udb.get_requirements(urs["id"])
    assert len(saved) == 1
    assert saved[0]["section"] == "Functional Requirements"


def test_run_generation_job_fails_when_every_batch_errors(db_path, isolated_gateway):
    urs = _make_urs()

    def fake_down(contents, config):
        raise genai_errors.ServerError(503, {"message": "down", "status": "UNAVAILABLE"})

    _register(isolated_gateway, "gemini", fake_down)
    _register(isolated_gateway, "nemotron", fake_down)

    gen_job._run_generation_job(urs["id"], urs, [["Functional Requirements"]])

    status = udb.get_generation_status(urs["id"])
    assert status["generation_status"] == "failed"
    assert status["generation_result_count"] == 0


def test_generate_batch_retries_on_max_tokens_truncation_then_succeeds(db_path, isolated_gateway):
    urs = _make_urs()
    calls = []

    def fake_gemini(contents, config):
        calls.append(1)
        if len(calls) == 1:
            return _FakeResponse(
                '[{"section": "Functional Requirements", "requirement": "cut off',
                finish_reason=types.FinishReason.MAX_TOKENS,
            )
        return _FakeResponse(_req_json("Functional Requirements"))

    _register(isolated_gateway, "gemini", fake_gemini)
    _register(isolated_gateway, "nemotron", _refuse("nemotron"))

    reqs, note = gen_job._generate_batch_resilient(urs["id"], 1, 1, urs, ["Functional Requirements"])

    # MAX_TOKENS truncation is a *content* problem on a call the gateway
    # completed successfully (no exception) — this is entirely layer-3
    # (URS-level) retry, invisible to and unaffected by the gateway's own
    # retry/fallback (which only ever fires on a raised exception).
    assert len(calls) == 2  # retried once after the MAX_TOKENS truncation
    assert note is None     # second attempt parsed cleanly, no fallback needed
    assert len(reqs) == 1


def test_generate_batch_does_not_retry_safety_block(db_path, isolated_gateway):
    urs = _make_urs()
    calls = []

    def fake_gemini(contents, config):
        calls.append(1)
        return _FakeResponse("", finish_reason=types.FinishReason.SAFETY)

    _register(isolated_gateway, "gemini", fake_gemini)
    _register(isolated_gateway, "nemotron", _refuse("nemotron"))

    with pytest.raises(gen_job.GenerationBlockedError):
        gen_job._generate_batch_resilient(urs["id"], 1, 1, urs, ["Functional Requirements"])

    # A SAFETY finish_reason on a successfully-returned response is a
    # content-level rejection the gateway never sees (it only classifies
    # raised exceptions) — never retried, never falls back to nemotron.
    assert len(calls) == 1


def test_generate_batch_does_not_add_urs_level_retry_on_top_of_gateway_retry(db_path, isolated_gateway):
    """Both providers are genuinely, persistently down (raised exceptions,
    not content problems). The gateway itself retries once on gemini,
    starts cooldown, falls back to nemotron and retries once there too
    (Stage 1's bounded-retry-per-provider contract) — 4 calls total inside
    ONE _generate_batch() invocation. The URS-level retry loop
    (_generate_batch_resilient) must NOT add a further retry on top of
    that: router.ProviderCallError is not _RetryableGenerationError, so it
    propagates on the URS layer's FIRST and only top-level attempt. This is
    the requirement-3/testing-requirement 'no duplicate/excessive retries
    caused by gateway + URS retry interaction' case."""
    urs = _make_urs()
    gemini_calls = []
    nemotron_calls = []

    def fake_gemini(contents, config):
        gemini_calls.append(1)
        raise genai_errors.ServerError(503, {"message": "down", "status": "UNAVAILABLE"})

    def fake_nemotron(contents, config):
        nemotron_calls.append(1)
        raise genai_errors.ServerError(503, {"message": "down", "status": "UNAVAILABLE"})

    _register(isolated_gateway, "gemini", fake_gemini)
    _register(isolated_gateway, "nemotron", fake_nemotron)

    with pytest.raises(ai_router.ProviderCallError):
        gen_job._generate_batch_resilient(urs["id"], 1, 1, urs, ["Functional Requirements"])

    assert len(gemini_calls) == 2    # gateway's own bounded retry, once
    assert len(nemotron_calls) == 2  # gateway's own bounded retry on the fallback, once
    # Total = 4, driven entirely by the gateway's Stage-1 contract — NOT
    # multiplied by URS_GENERATION_MAX_RETRIES (which would be 4 * 3 = 12
    # if the URS layer were (incorrectly) also retrying this failure).


def test_gateway_retry_and_urs_retry_compound_additively_not_multiplicatively(db_path, isolated_gateway):
    """A single batch where BOTH retry layers fire in sequence: gemini's
    first call is a transient exception (gateway retries internally, 2nd
    call succeeds but with malformed content), which the URS layer then
    retries as its own top-level attempt (3rd call, valid content this
    time). If the two layers were incorrectly multiplying instead of
    composing, this would need up to 3 URS attempts * 2 gateway attempts =
    6 calls; the correct, bounded behavior is exactly 3."""
    urs = _make_urs()
    calls = []

    def fake_gemini(contents, config):
        calls.append(1)
        if len(calls) == 1:
            raise genai_errors.ServerError(503, {"message": "down", "status": "UNAVAILABLE"})
        if len(calls) == 2:
            return _FakeResponse('[{"section": "Functional Requirements", "requirement": "cut off')
        return _FakeResponse(_req_json("Functional Requirements"))

    _register(isolated_gateway, "gemini", fake_gemini)
    _register(isolated_gateway, "nemotron", _refuse("nemotron"))

    reqs, note = gen_job._generate_batch_resilient(urs["id"], 1, 1, urs, ["Functional Requirements"])

    assert len(calls) == 3
    assert note is None  # the URS layer's 2nd top-level attempt parsed cleanly
    assert len(reqs) == 1


def test_generate_batch_quota_failure_skips_retry_and_falls_back_immediately(db_path, isolated_gateway):
    urs = _make_urs()
    gemini_calls = []
    nemotron_calls = []

    def fake_gemini(contents, config):
        gemini_calls.append(1)
        raise genai_errors.ClientError(429, {"message": "Resource exhausted", "status": "RESOURCE_EXHAUSTED"})

    def fake_nemotron(contents, config):
        nemotron_calls.append(1)
        return _FakeResponse(_req_json("Functional Requirements"))

    _register(isolated_gateway, "gemini", fake_gemini)
    _register(isolated_gateway, "nemotron", fake_nemotron)

    assert not isolated_gateway._in_cooldown("gemini")

    reqs, note = gen_job._generate_batch_resilient(urs["id"], 1, 1, urs, ["Functional Requirements"])

    assert len(gemini_calls) == 1     # NOT retried — quota failures skip the same-provider retry
    assert len(nemotron_calls) == 1   # immediate fallback, one attempt, succeeds
    assert note is None
    assert len(reqs) == 1
    assert isolated_gateway._in_cooldown("gemini")  # circuit breaker engaged


def test_generate_batch_falls_back_to_partial_extraction_after_retries_exhausted(db_path, isolated_gateway):
    urs = _make_urs()
    calls = []
    truncated = (
        '[{"section": "Functional Requirements", "requirement": "The system shall do A.", '
        '"priority": "High", "gmp_criticality": "GMP"}, '
        '{"section": "Functional Requirements", "requirement": "The system shall do B'
    )

    def fake_gemini(contents, config):
        calls.append(1)
        return _FakeResponse(truncated)  # always malformed (but successfully returned) on every attempt

    _register(isolated_gateway, "gemini", fake_gemini)
    _register(isolated_gateway, "nemotron", _refuse("nemotron"))

    reqs, note = gen_job._generate_batch_resilient(urs["id"], 1, 1, urs, ["Functional Requirements"])

    assert len(calls) == 3  # 1 initial + 2 retries (config.URS_GENERATION_MAX_RETRIES default)
    assert note is not None
    assert len(reqs) == 1
    assert reqs[0]["requirement"] == "The system shall do A."


def test_generate_batch_empty_output_is_never_persisted_as_success(db_path, isolated_gateway):
    """Empty AI output must remain a generation failure end-to-end, never
    be silently persisted as though it were a successful (if unhelpful)
    result — requirement 5. An empty string on every attempt fails JSON
    parsing every time, is retried at the URS level like any other
    malformed content, and — since there is nothing to salvage — the batch
    (and, being the only batch, the whole job) ends up failed with zero
    requirements persisted."""
    urs = _make_urs()

    def fake_gemini(contents, config):
        return _FakeResponse("")  # successful call, empty text, every attempt

    _register(isolated_gateway, "gemini", fake_gemini)
    _register(isolated_gateway, "nemotron", _refuse("nemotron"))

    gen_job._run_generation_job(urs["id"], urs, [["Functional Requirements"]])

    status = udb.get_generation_status(urs["id"])
    assert status["generation_status"] == "failed"
    assert status["generation_result_count"] == 0
    assert udb.get_requirements(urs["id"]) == []


def test_extract_partial_requirements_recovers_complete_objects_and_drops_truncated_trailing_one():
    truncated = (
        '[{"section": "Functional Requirements", "requirement": "A complete one.", '
        '"priority": "High", "gmp_criticality": "GMP"}, '
        '{"section": "Functional Requirements", "requirement": "cut off mid'
    )
    recovered = gen_job._extract_partial_requirements(truncated)
    assert len(recovered) == 1
    assert recovered[0]["requirement"] == "A complete one."


def test_build_generation_message_reports_partial_section_coverage():
    msg = gen_job._build_generation_message(
        ["Functional Requirements", "Safety Requirements", "GMP Requirements"],
        {"Functional Requirements", "GMP Requirements"},
        11,
    )
    assert msg == (
        "2 of 3 sections generated successfully (11 requirements). "
        "1 section failed and can be retried: Safety Requirements."
    )


def test_build_generation_message_full_success_has_no_failure_clause():
    msg = gen_job._build_generation_message(
        ["Functional Requirements", "Safety Requirements"],
        {"Functional Requirements", "Safety Requirements"},
        7,
    )
    assert msg == "2 of 2 sections generated successfully (7 requirements)."


def test_parse_ai_requirements_strips_markdown_fences():
    raw = "Here you go:\n```json\n" + _req_json("Functional Requirements") + "\n```"
    parsed = gen_job._parse_ai_requirements(raw)
    assert len(parsed) == 1
    assert parsed[0]["section"] == "Functional Requirements"


def test_batch_sections_respects_batch_size():
    sections = ["A", "B", "C", "D", "E"]
    assert gen_job._batch_sections(sections, 2) == [["A", "B"], ["C", "D"], ["E"]]


# ── Atomic status/count writes (Stabilization Iteration 2, priority 2) ─────
# Regression coverage for the root cause of the old "59 requirements
# generated" / "taking longer than expected" contradiction: the final
# result_count used to be published (via update_generation_progress) before
# a separate, later finish_generation() call flipped generation_status to a
# terminal value — a poll landing in that gap saw a "final" count next to a
# non-terminal status. These tests assert the fix's two load-bearing
# properties: requirements are persisted per-batch as they complete (not
# once at the very end), and finish_generation() always publishes
# progress_current == progress_total together with the terminal status and
# result_count in the one call that ends the job.

def test_requirements_are_persisted_incrementally_per_batch(db_path, isolated_gateway):
    urs = _make_urs()
    seen_after_first_batch = {}

    def fake_gemini(contents, config):
        prompt_text = contents[0].parts[0].text
        if "Safety Requirements" in prompt_text:
            # By the time the second batch's AI call happens, the first
            # batch's requirement must already be in the database — proof
            # persistence happens per-batch, not in one bulk save at the end.
            seen_after_first_batch["count"] = len(udb.get_requirements(urs["id"]))
            return _FakeResponse(_req_json("Safety Requirements"))
        return _FakeResponse(_req_json("Functional Requirements"))

    _register(isolated_gateway, "gemini", fake_gemini)
    _register(isolated_gateway, "nemotron", _refuse("nemotron"))

    gen_job._run_generation_job(
        urs["id"], urs, [["Functional Requirements"], ["Safety Requirements"]],
    )

    assert seen_after_first_batch["count"] == 1
    assert len(udb.get_requirements(urs["id"])) == 2


def test_finish_generation_always_sets_progress_current_equal_to_total(db_path, isolated_gateway):
    urs = _make_urs()

    def fake_gemini(contents, config):
        return _FakeResponse(_req_json("Functional Requirements"))

    _register(isolated_gateway, "gemini", fake_gemini)
    _register(isolated_gateway, "nemotron", _refuse("nemotron"))

    gen_job._run_generation_job(
        urs["id"], urs, [["Functional Requirements"], ["Safety Requirements"]],
    )

    status = udb.get_generation_status(urs["id"])
    assert status["generation_status"] == "completed"
    assert status["generation_progress_current"] == status["generation_progress_total"] == 2
    # The requirement actually persisted for the *last* batch to complete
    # must already be reflected in generation_result_count at the exact
    # moment status becomes terminal — both are written by the same
    # statement in finish_generation(), so this can never be observed any
    # other way.
    assert status["generation_result_count"] == len(udb.get_requirements(urs["id"]))


def test_finish_generation_writes_status_progress_and_count_atomically(db_path):
    """Direct unit check on finish_generation() itself: a single call sets
    status, progress_current/total, and result_count together — there is no
    way to observe one without the others already being consistent."""
    urs = _make_urs()
    udb.start_generation(urs["id"], total_batches=3)

    udb.finish_generation(urs["id"], "completed", 3, 7, "", "3 of 3 sections generated (7 requirements).")

    status = udb.get_generation_status(urs["id"])
    assert status["generation_status"] == "completed"
    assert status["generation_progress_current"] == 3
    assert status["generation_progress_total"] == 3
    assert status["generation_result_count"] == 7


def test_append_requirements_does_not_touch_existing_rows(db_path):
    urs = _make_urs()
    udb.save_requirements(urs["id"], [
        {"req_id": "REQ-001", "section": "General", "requirement": "Pre-existing requirement."},
    ])

    udb.append_requirements(urs["id"], [
        {"req_id": "REQ-002", "section": "Functional", "requirement": "Newly appended requirement."},
    ])

    reqs = udb.get_requirements(urs["id"])
    assert len(reqs) == 2
    assert {r["req_id"] for r in reqs} == {"REQ-001", "REQ-002"}
