"""Analytical instruments: HPLC, GC, UV Spectrophotometer."""

from pharmagpt.equipment import EquipmentProfile, _register

# ─── HPLC ────────────────────────────────────────────────────────────────────

_register(EquipmentProfile(
    name="HPLC",
    aliases=["high performance liquid chromatograph", "high-performance liquid chromatography",
             "liquid chromatograph", "hplc system", "uplc", "uhplc"],
    description=(
        "A High-Performance Liquid Chromatography (HPLC) system is an analytical instrument "
        "used for separation, identification, and quantification of pharmaceutical compounds. "
        "It comprises a solvent delivery system (pump), autosampler, column oven, UV/DAD/MS "
        "detector, and data acquisition software (CDS). Governed by 21 CFR Part 11 for "
        "electronic records and 21 CFR Part 211.68 for computerised systems."
    ),
    applicable_regulations=[
        "21 CFR Part 211.68 — Computerised systems in laboratory environments",
        "21 CFR Part 211.194 — Laboratory records",
        "EU GMP Annex 11 — Computerised systems",
        "EU GMP Annex 15 — Qualification and Validation",
        "ICH Q2(R1) — Validation of analytical procedures",
        "USP <621> — Chromatography",
        "USP <1058> — Analytical Instrument Qualification (AIQ)",
        "GAMP 5 — Software categorisation and CSV requirements",
        "OECD GLP Principles — for regulatory submission use",
        "ICH Q10 — Pharmaceutical Quality System",
    ],
    required_utilities=[
        "Electrical supply: 220–240 V AC, 50 Hz, ≥15 A dedicated circuit with UPS",
        "HPLC-grade solvents (Acetonitrile, Methanol, Water) with waste disposal",
        "Ultrapure water (Type 1, ≥18.2 MΩ·cm) via in-lab purification system",
        "Nitrogen or Helium gas supply for degassing (99.999% purity), 60–80 psi",
        "Stable ambient temperature: 18–25°C ± 2°C; relative humidity: 40–60% RH",
        "Vibration-free laboratory bench (anti-vibration mat recommended)",
        "Network/LAN connection for CDS server integration (if networked CDS)",
        "Fume extraction / solvent vapour management system",
    ],
    critical_components=[
        "Isocratic/binary/quaternary pump with pulse dampener",
        "Autosampler with temperature-controlled tray (4–8°C)",
        "Column oven / column compartment (temperature range: ambient to 60°C)",
        "UV/Vis / DAD / FLD / ELSD / MS detector",
        "Degasser (online vacuum or membrane type)",
        "Column (RP-C18, C8, HILIC, ion-exchange, etc.)",
        "Chromatography Data System (CDS) software (e.g., Empower, OpenLAB, Chromeleon)",
        "Injection valve / switching valve",
        "Back-pressure regulator",
        "Tubing, fittings, and union connectors (PEEK or stainless steel)",
    ],
    iq_checklist=[
        "Verify equipment model, serial numbers, and configuration against PO and URS",
        "Confirm instrument placement: bench stability, clearance, ventilation, and safety",
        "Verify all utility connections: electrical (voltage, phase, earthing), network",
        "Confirm solvent waste line routing to compliant waste container with secondary containment",
        "Verify firmware/software version matches qualification scope and 21 CFR Part 11 requirements",
        "Confirm CDS installation, user access levels, audit trail activation, and backup schedule",
        "Check all supplied accessories, spare parts, and certificates of conformity against packing list",
        "Verify column oven heating element, door seal, and thermostat probe installation",
        "Confirm autosampler needle assembly, wash station, and sample loop installation",
        "Verify pump head, check valves, and piston seal installation per manufacturer specs",
        "Check manufacturer's Certificate of Calibration (CoC) for detector lamp and flow cell",
        "Confirm instrument is registered in asset management system with unique equipment ID",
        "Verify emergency shutdown procedure, solvent interlock, and leak sensor functionality",
        "Confirm all cable connections (power, signal, data) per wiring diagram",
    ],
    oq_tests=[
        "Pump flow rate accuracy: target vs. actual at 0.5, 1.0, 1.5 mL/min (±2%)",
        "Pump pressure precision: RSD ≤ 0.5% across 10 consecutive readings",
        "Gradient accuracy: verify B% composition at 0%, 25%, 50%, 75%, 100% B (±1% absolute)",
        "Autosampler volume accuracy: 5, 10, 20 µL injections using caffeine standard (±2%)",
        "Autosampler carryover: ≤ 0.05% of previous peak area after blank injection",
        "Autosampler temperature: target ±2°C over 4 h (if cooling equipped)",
        "Column oven temperature accuracy and uniformity: target ±1°C at 25°C, 40°C",
        "Detector wavelength accuracy: 265 nm (caffeine) and 254 nm (naphthalene) ±2 nm",
        "Detector linearity: R² ≥ 0.999 across 5 concentration levels",
        "Detector noise / baseline drift: noise ≤ 1 × 10⁻⁴ AU; drift ≤ 5 × 10⁻⁴ AU/h",
        "System suitability with reference standard: N ≥ 2000 plates; tailing ≤ 2.0; Rs ≥ 1.5",
        "Audit trail verification: all system actions logged with timestamp and user ID",
        "Electronic records test: create, modify, and review records under different user roles",
        "Data backup and recovery test: simulate backup, restore, and verify data integrity",
    ],
    pq_tests=[
        "Method precision (repeatability): 6 injections of QC standard, RSD ≤ 1.0% for peak area",
        "Intermediate precision: analyst-to-analyst, day-to-day RSD ≤ 2.0%",
        "Accuracy/recovery: 80%, 100%, 120% of target concentration; 98.0–102.0% recovery",
        "Linearity across working range: R² ≥ 0.999 with residuals ≤ 2%",
        "LOD and LOQ determination for the analytical method",
        "Specificity/selectivity: no interfering peaks from placebo, excipients, or degradants",
        "Robustness: ±5% flow rate, ±5°C column temp, ±2 nm wavelength — results within acceptance",
        "System suitability performance over a full working day (8 h continuous run)",
        "Column lifetime tracking: retention time stability over ≥ 200 injections",
        "Analyst training verification: results from two analysts within 2% of each other",
    ],
    calibration_points=[
        "Pump flow rate (0.5, 1.0, 1.5, 2.0 mL/min) — gravimetric method",
        "Detector wavelength accuracy (254, 265, 313, 334 nm reference filters)",
        "Detector absorbance linearity (holmium oxide or NIST traceable standards)",
        "Column oven temperature (ambient +5, 30, 40, 50°C — NIST-traceable probe)",
        "Autosampler injection volume (5, 10, 20, 50 µL)",
        "Pressure transducer / pressure gauge (0, 50, 100, 150, 200 bar)",
        "Chromatography Data System clock synchronisation (against NTP server)",
    ],
    safety_checks=[
        "Solvent leak detection system functional and alarm tested",
        "Electrical earthing continuity verified (< 1 Ω)",
        "Emergency power-off switch accessible and labelled",
        "Fume extraction / LEV operational with face velocity ≥ 0.5 m/s",
        "Secondary containment tray for solvent bottles in place and intact",
        "SDS for all solvents available and reviewed by operators",
        "Fire extinguisher (CO₂ or dry chemical) within 10 m of instrument",
        "No electrical cables routed through solvent spill zones",
    ],
    documentation_checklist=[
        "Vendor IQ/OQ documentation package (factory test certificates)",
        "Manufacturer's Operation and Maintenance Manual",
        "Certificate of Calibration for detector (lamp hours, flow cell)",
        "Software validation report / CSV package (21 CFR Part 11 compliance)",
        "Approved analytical method SOP referencing this instrument",
        "Instrument logbook (unique ID, maintenance, calibration, usage entries)",
        "Calibration certificates for all reference standards used in OQ/PQ",
        "Training records for all authorised operators",
        "Preventive Maintenance SOP and schedule",
        "Column qualification certificate or suitability test data",
    ],
    standard_acceptance_criteria=[
        "Flow rate accuracy: ±2% of set value",
        "Gradient composition accuracy: ±1% absolute at each set point",
        "Injection volume accuracy: ±2% of set value",
        "Autosampler carryover: ≤ 0.05%",
        "Column oven temperature accuracy: ±1°C",
        "Detector wavelength accuracy: ±2 nm",
        "Detector baseline noise: ≤ 1 × 10⁻⁴ AU",
        "System suitability: N ≥ 2000 plates; tailing factor ≤ 2.0; Rs ≥ 1.5",
        "Method precision (RSD): ≤ 1.0% (6 injections)",
        "Linearity: R² ≥ 0.999 across validated range",
        "Audit trail: 100% traceability of all data events",
    ],
    common_deviations=[
        "Ghost peaks or baseline disturbances due to solvent impurities — verify HPLC-grade solvents",
        "Pump pressure fluctuation exceeding ±5 bar — check seal wear and check valves",
        "Autosampler needle blockage causing missed injections — include needle wash SOP",
        "Retention time drift > 2% over sequence — assess column equilibration and temperature stability",
        "CDS audit trail not activated prior to use — enforce pre-use checklist",
        "Carryover > 0.05% — assess wash solvent and needle wipe step adequacy",
        "Software version mismatch between IQ scope and installed version",
        "Column certificate missing from instrument file — track column serial in logbook",
    ],
))


# ─── GC ──────────────────────────────────────────────────────────────────────

_register(EquipmentProfile(
    name="GC",
    aliases=["gas chromatograph", "gas chromatography", "gc system",
             "gc-fid", "gc-ms", "gc/ms", "headspace gc"],
    description=(
        "A Gas Chromatography (GC) system separates and quantifies volatile and semi-volatile "
        "compounds in pharmaceutical products. Typical configuration includes a split/splitless "
        "injector, capillary column inside an oven, and FID, TCD, ECD, or MS detector. Used for "
        "residual solvents (ICH Q3C), organic volatile impurities (USP <467>), and raw material "
        "identification. Computerised data systems require 21 CFR Part 11 / Annex 11 compliance."
    ),
    applicable_regulations=[
        "21 CFR Part 211.194 — Laboratory records",
        "21 CFR Part 211.68 — Computerised systems",
        "EU GMP Annex 11 — Computerised systems",
        "EU GMP Annex 15 — Qualification and Validation",
        "ICH Q3C — Residual Solvents guideline",
        "ICH Q2(R1) — Validation of analytical procedures",
        "USP <467> — Residual Solvents",
        "USP <1058> — Analytical Instrument Qualification (AIQ)",
        "GAMP 5 — for CDS software categorisation",
    ],
    required_utilities=[
        "Carrier gas: Helium (99.999% ultra-high purity) or Hydrogen, 60–100 psi regulated supply",
        "Detector gas: Hydrogen (FID) 99.999% and air (zero grade) for FID detector",
        "Make-up gas: Nitrogen (FID) or Helium for MS",
        "Electrical: 220–240 V AC, 50 Hz, ≥ 20 A dedicated breaker",
        "Compressed air: zero-grade, particle-free, oil-free for pneumatic controls",
        "Stable lab temperature: 18–25°C; humidity 40–60% RH",
        "Network connection for CDS integration",
        "Fume cupboard or LEV for venting FID exhaust and septum bleed",
        "Fire suppression — hydrogen gas detector alarm linked to auto-shutoff",
    ],
    critical_components=[
        "Injector (split/splitless, PTV, on-column, headspace) with liner and septum",
        "Capillary column (stationary phase: DB-1, DB-5, WAX, etc.; length, ID, film thickness)",
        "Column oven with precise temperature programming controller",
        "FID / TCD / ECD / MS detector",
        "Electronic Pressure Control (EPC) modules",
        "Autosampler / headspace sampler (if applicable)",
        "CDS software with 21 CFR Part 11 audit trail",
        "Gas purifier traps (moisture, oxygen) inline on carrier gas line",
        "Detector electrometer and collector assembly",
    ],
    iq_checklist=[
        "Verify instrument model, serial numbers, and module configuration against PO/URS",
        "Confirm gas supply connections, regulator pressures, and leak testing of all fittings",
        "Verify hydrogen gas detector installation, alarm setpoint (10% LEL), and interlock",
        "Confirm CDS software installation, version, user roles, and audit trail activation",
        "Check column installation: part number, serial, phase, length, ID, film thickness recorded",
        "Verify injector liner, septum, and ferrule installation per manufacturer specification",
        "Confirm detector (FID) ignition, flame sensor, and jet assembly integrity",
        "Check electrical connections, earthing, and power conditioner if specified",
        "Verify oven door seal integrity and fan operation",
        "Confirm carrier and detector gas purifier trap installation and installation dates",
        "Verify all accessories received and documented: syringes, liners, septa, columns",
        "Confirm instrument registered in asset management system with unique ID",
    ],
    oq_tests=[
        "Carrier gas flow rate accuracy: set vs. measured at 1.0, 2.0, 3.0 mL/min (±5%)",
        "Oven temperature accuracy: isothermal at 50°C, 100°C, 150°C, 200°C (±2°C)",
        "Oven temperature programming: rate accuracy ±2°C/min, hold time ±30 s",
        "Injector temperature accuracy: 150°C, 200°C, 250°C (±3°C)",
        "Detector temperature accuracy: 200°C, 250°C, 300°C (±3°C)",
        "FID sensitivity test: S/N ≥ 50 with 1 ng octane injection",
        "Splitless injection: peak area RSD ≤ 2% for 5 replicate injections",
        "Retention time reproducibility: RSD ≤ 0.5% for 5 consecutive injections",
        "Linearity of detector response: R² ≥ 0.999 across 5 concentration levels",
        "Autosampler accuracy and precision: volume RSD ≤ 2% (if equipped)",
        "Audit trail: all system events logged with timestamp, user, action, and old/new values",
    ],
    pq_tests=[
        "Method precision for residual solvents: RSD ≤ 5% for 6 injections at reporting threshold",
        "Accuracy/recovery: spike recovery 90–110% at 50%, 100%, 150% of concentration limit",
        "Specificity: no co-elution of Class 1/2 solvents with matrix peaks (full resolution)",
        "Linearity: R² ≥ 0.999 from LOQ to 150% of specification",
        "LOQ verification: S/N ≥ 10 at LOQ level",
        "Robustness: ±10°C oven temp, ±10% carrier flow — results within acceptance criteria",
        "Analyst cross-validation: two analysts, same method, RSD ≤ 5% between datasets",
        "System suitability over full 8-hour analytical sequence",
    ],
    calibration_points=[
        "Oven temperature (50°C, 100°C, 150°C, 200°C, 250°C) with NIST-traceable thermocouple",
        "Injector temperature (150°C, 200°C, 250°C)",
        "Detector temperature (200°C, 250°C, 300°C)",
        "Electronic Pressure Control (EPC) at 10, 30, 60 psi — vs. calibrated reference gauge",
        "Carrier gas flow rate (0.5, 1.0, 2.0, 3.0 mL/min) — soap bubble or electronic flowmeter",
        "Detector sensitivity / signal calibration (using certified reference standard)",
    ],
    safety_checks=[
        "Hydrogen gas detector alarm functional at ≤ 10% LEL — tested monthly",
        "Automatic gas shutoff interlock operational on H₂ alarm",
        "Oven thermal runaway protection: max temperature limiter verified",
        "FID ignition failure alarm tested — system does not ignite without gas flow confirmed",
        "All gas fittings leak-tested with electronic sniffer or soap solution annually",
        "Electrical earthing ≤ 1 Ω; no unshielded cables near high-temperature zones",
        "Fire extinguisher (CO₂) within 10 m; no Class B solvent stored near instrument",
    ],
    documentation_checklist=[
        "Vendor factory test certificate and installation certificate",
        "Column certificate of analysis (phase, dimensions, efficiency, bleed)",
        "CDS validation package (CSV report, 21 CFR Part 11 assessment)",
        "Gas supply certificates of purity",
        "Instrument logbook (usage, maintenance, column changes, deviations)",
        "Approved SOP for method operation",
        "Calibration certificates for all reference standards",
        "Training records for authorised analysts",
        "Preventive Maintenance schedule and completed PM records",
    ],
    standard_acceptance_criteria=[
        "Oven temperature accuracy: ±2°C at each set point",
        "Injector temperature accuracy: ±3°C",
        "Carrier gas flow accuracy: ±5%",
        "Retention time reproducibility: RSD ≤ 0.5%",
        "Peak area reproducibility: RSD ≤ 2% (routine); ≤ 5% (trace analysis)",
        "Detector linearity: R² ≥ 0.999",
        "Recovery/accuracy: 90–110% at all concentration levels",
        "Audit trail: 100% event capture with no gaps",
    ],
    common_deviations=[
        "Septum bleed causing ghost peaks — schedule septum replacement every 50–100 injections",
        "Column conditioning not completed, causing stationary phase bleed",
        "FID flame extinction during run — check gas ratios and flow continuity",
        "Hydrogen gas alarm nuisance trips — verify alarm threshold calibration",
        "Retention time drift due to column ageing or inlet contamination",
        "Liner silylation breakdown leading to active sites and peak tailing",
        "CDS audit trail disabled or not backed up — enforce pre-sequence checklist",
    ],
))


# ─── UV Spectrophotometer ─────────────────────────────────────────────────────

_register(EquipmentProfile(
    name="UV SPECTROPHOTOMETER",
    aliases=["uv spectrophotometer", "uv-vis spectrophotometer", "uv/vis",
             "uv-visible spectrophotometer", "spectrophotometer", "uv spectrometer"],
    description=(
        "A UV/Vis Spectrophotometer measures the absorbance or transmittance of light in the "
        "ultraviolet (190–400 nm) and visible (400–800 nm) range by pharmaceutical samples. "
        "Used for assay, dissolution testing, identification, and purity determination. "
        "Instrument types include single-beam and double-beam configurations. Data may be "
        "integrated with laboratory information management systems (LIMS)."
    ),
    applicable_regulations=[
        "21 CFR Part 211.194 — Laboratory records",
        "EU GMP Annex 11 — Computerised systems (if networked)",
        "USP <857> — Ultraviolet-Visible Spectrophotometry",
        "USP <1058> — Analytical Instrument Qualification (AIQ)",
        "ICH Q2(R1) — Validation of analytical procedures",
        "EP 2.2.25 — Absorption Spectrophotometry, Ultraviolet and Visible",
        "ASTM E275 — Describing and measuring UV-Vis performance",
        "ISO 7027 — Water quality (turbidity by UV if applicable)",
    ],
    required_utilities=[
        "Electrical: 220–240 V AC, 50 Hz, 10 A dedicated circuit",
        "Stable ambient temperature: 15–30°C (optimum 22±3°C)",
        "Relative humidity: ≤ 80% RH non-condensing",
        "Vibration-free bench (spectrophotometers are sensitive to mechanical shock)",
        "Purge gas (dry nitrogen or argon) for measurements below 200 nm (optional)",
        "Ultrapure water (Type 1) for blank and reference solutions",
        "Fume extraction if volatile solvents used in cuvette preparation",
    ],
    critical_components=[
        "Deuterium lamp (UV range: 190–400 nm) with lamp hours counter",
        "Tungsten/halogen lamp (Vis range: 320–1100 nm)",
        "Monochromator (grating or prism) and wavelength drive motor",
        "Photomultiplier tube (PMT) or photodiode array detector",
        "Cuvette holder (single / dual beam, 10 mm path length standard)",
        "Reference beam optical path (double-beam instruments)",
        "Wavelength calibration mechanism (holmium oxide filter or holmium glass)",
        "Data acquisition and processing software",
        "Stray light filter assembly",
    ],
    iq_checklist=[
        "Verify instrument model, serial number, and lamp type against PO/URS",
        "Confirm placement: stable bench, no direct sunlight or strong UV sources nearby",
        "Verify deuterium and tungsten lamp installation dates and lamp hours = 0 (new lamps)",
        "Check cuvette holder alignment and optical path cleanliness",
        "Confirm software installation, version, user access, and audit trail configuration",
        "Verify all cuvette standards, reference filters, and accessories received",
        "Confirm electrical connections, earthing, and power supply within specification",
        "Check instrument is registered in asset management system",
        "Verify monochromator covers and optical bench for shipping damage",
        "Confirm wavelength scan range limits (190–1100 nm or as specified)",
    ],
    oq_tests=[
        "Wavelength accuracy: holmium oxide / holmium glass filter peaks at 241.5, 287.5, 361.5 nm (±1 nm)",
        "Wavelength repeatability: 3 consecutive scans of holmium filter, ±0.5 nm",
        "Photometric accuracy: 0.1, 0.5, 1.0 AU with NIST-traceable neutral density filters (±0.01 AU)",
        "Photometric linearity: R² ≥ 0.999 across 0–2 AU range",
        "Stray light test: 1% KCl solution at 198 nm — absorbance ≥ 2 AU",
        "Photometric noise: RMS noise ≤ 0.0005 AU at 500 nm",
        "Baseline flatness: ±0.001 AU across 400–800 nm with matched cuvettes",
        "Scan speed accuracy: fast/medium/slow scan modes — no wavelength shift",
        "Lamp stability: absorbance drift < 0.001 AU/min after 30 min warm-up",
        "Software audit trail: all instrument actions logged with timestamp and user",
    ],
    pq_tests=[
        "Method precision: 6 replicate measurements of assay standard, RSD ≤ 0.5%",
        "Accuracy: 80%, 100%, 120% standard recovery 98.0–102.0%",
        "Linearity of Beer-Lambert law across working concentration range: R² ≥ 0.999",
        "Specificity: no absorbance contribution from placebo at analytical wavelength",
        "Robustness: measurements at ±1 nm wavelength deviation — results within ±1%",
        "System suitability: absorbance of reference standard within ±1% of specification",
        "Analyst cross-validation: two analysts, RSD ≤ 1% between datasets",
    ],
    calibration_points=[
        "Wavelength accuracy (241.5, 287.5, 361.5 nm) using holmium glass — NIST traceable",
        "Photometric accuracy (0.1, 0.5, 1.0 AU) — NIST-traceable neutral density filters",
        "Stray light (KCl solution, 198 nm)",
        "Photometric linearity (5-point dilution series)",
        "Deuterium and tungsten lamp intensity / energy output at service intervals",
    ],
    safety_checks=[
        "UV radiation interlock: instrument shutter closes when cuvette compartment is open",
        "Ozone generation alert: ensure lab ventilation is adequate for UV operation below 220 nm",
        "Electrical earthing verified ≤ 1 Ω",
        "Lamp replacement procedure: cool-down period (30 min) and UV-protective gloves required",
        "Solvent vapour from sample preparation — fume extraction or closed cuvette systems",
    ],
    documentation_checklist=[
        "Vendor factory test certificate and certificate of conformance",
        "Holmium oxide / neutral density filter certificates (NIST traceable)",
        "Software validation report (if CDS-integrated)",
        "Instrument logbook (lamp changes, maintenance, calibration, deviations)",
        "Approved SOP for instrument operation and cleaning",
        "Training records for all authorised operators",
        "Preventive Maintenance SOP and schedule",
        "Cuvette qualification records (matched pair verification)",
    ],
    standard_acceptance_criteria=[
        "Wavelength accuracy: ±1 nm at holmium reference peaks",
        "Photometric accuracy: ±0.01 AU or ±1% (whichever is greater)",
        "Photometric linearity: R² ≥ 0.999",
        "Stray light: absorbance ≥ 2 AU at 198 nm (1% KCl)",
        "Baseline noise: ≤ 0.0005 AU RMS",
        "Method precision: RSD ≤ 0.5%",
        "Accuracy: 98.0–102.0% recovery",
    ],
    common_deviations=[
        "Wavelength drift due to aged grating drive — check lamp hours and recalibrate",
        "High stray light after deuterium lamp ageing — lamp replacement required",
        "Cuvette scratches causing photometric scatter — inspect and replace cuvettes",
        "Baseline drift during first 10 minutes — enforce 30-minute warm-up in SOP",
        "Matched cuvette pair qualification not documented — include in instrument file",
        "Audit trail not enabled before use — enforce system login SOP",
    ],
))
