"""Manufacturing equipment: Tablet Compression Machine, Capsule Filling Machine."""

from equipment import EquipmentProfile, _register

# ─── Tablet Compression Machine ──────────────────────────────────────────────

_register(EquipmentProfile(
    name="TABLET COMPRESSION MACHINE",
    aliases=["tablet press", "rotary tablet press", "tablet compression", "tablet compressor",
             "single punch press", "multi-station press", "tablet punching machine",
             "rotary press", "compression machine"],
    description=(
        "A Tablet Compression Machine (Rotary Tablet Press) converts powder blends or granules "
        "into tablets of defined weight, thickness, hardness, and diameter. Multi-station rotary "
        "presses (16–75 stations) with pre-compression and main compression rollers are standard "
        "in pharmaceutical manufacturing. Critical process parameters (CPPs): compression force, "
        "turret speed, and pre-compression force. Governed by 21 CFR Part 211 and EU GMP."
    ),
    applicable_regulations=[
        "21 CFR Part 211.65 — Equipment construction",
        "21 CFR Part 211.68 — Automatic, mechanical, and electronic equipment",
        "21 CFR Part 211.100 — Written procedures; deviations",
        "EU GMP Chapter 3 — Premises and Equipment",
        "EU GMP Annex 15 — Qualification and Validation",
        "ICH Q8(R2) — Pharmaceutical Development",
        "ICH Q10 — Pharmaceutical Quality System",
        "Schedule M — Good Manufacturing Practices (India)",
        "ISPE Baseline Guide Vol. 5 — Commissioning and Qualification",
    ],
    required_utilities=[
        "Electrical: 380–415 V, 3-phase, 50 Hz; control panel 220–240 V, 50 Hz",
        "Compressed air: clean, dry, oil-free, 6–8 bar (for die/punch lubrication, dust extraction)",
        "Dust extraction: local exhaust ventilation connected to centralised or stand-alone collector",
        "Cooling water: for punch/die cooling in high-speed presses (closed loop, 15–20°C)",
        "Cleanroom: Grade D or controlled environment, 20–25°C, 45–55% RH (product-dependent)",
        "Lubricant spray system: PTFE or external lubricant (if magnesium stearate-free formulation)",
    ],
    critical_components=[
        "Turret (upper and lower punch guides, die table, 16–75 stations)",
        "Punches and dies (TSM/EU-B standard, hardened steel, punch tip geometry)",
        "Pre-compression roller assembly (force transducer)",
        "Main compression roller assembly (force transducer)",
        "Tablet ejection cam and ejection ramp",
        "Paddle feeder / gravity feeder with fill cam adjustment",
        "Tablet discharge chute and metal detector integration point",
        "Dust extraction ports and powder containment seals",
        "Weight control system (in-process weight monitoring, auto-rejection)",
        "HMI / PLC with recipe management, batch record generation",
        "Force transducers for pre- and main compression (calibrated)",
    ],
    iq_checklist=[
        "Verify press model, number of stations, compression force range against URS/PO",
        "Confirm materials of product-contact parts: 316L SS, food-grade lubricants, no copper",
        "Verify turret assembly: punch guides, die table, and die bore dimensions",
        "Check punch and die set: material certificate, tip geometry, dimensional report (TSM/EU-B)",
        "Confirm pre-compression and main compression force transducer installation",
        "Verify HMI/PLC software version, recipe management, and audit trail configuration",
        "Check dust extraction connection: flow rate adequate for product containment",
        "Verify weight monitoring system: rejection system installation and pneumatic supply",
        "Confirm all lubricated points use food-grade or pharma-grade lubricants only",
        "Check electrical interlocks: safety guard switches, turret guard, feed frame guard",
        "Verify instrument registration in asset management system with unique ID",
        "Check accessibility for cleaning: no dead-legs, crevices, or inaccessible zones",
        "Confirm calibration equipment (weights, force gauge) available for OQ",
    ],
    oq_tests=[
        "Turret speed accuracy: 10, 20, 30, 40 RPM — actual vs. set ±2%",
        "Pre-compression force accuracy: 2, 5, 10 kN — calibrated force gauge ±2%",
        "Main compression force accuracy: 10, 20, 40, 60, 80 kN — calibrated force gauge ±2%",
        "Tablet weight uniformity at target press speed: 20 tablets, RSD ≤ 2%",
        "Tablet thickness uniformity: 20 tablets, RSD ≤ 2% (related to die fill)",
        "Turret speed stability: ±1 RPM variation over 10-minute run",
        "Tablet ejection test: no sticking, capping, lamination at OQ conditions",
        "Weight control rejection system: ejection of simulated OOW tablets verified (100% rejection)",
        "HMI recipe save/load: verify CPP values retained after recipe switch",
        "Audit trail: all parameter changes logged with user, timestamp, old and new values",
        "Interlock test: press stops immediately when guard is opened during operation",
        "Dust extraction: airflow at press ports ≥ 0.5 m/s face velocity",
    ],
    pq_tests=[
        "Tablet weight uniformity over full batch run: RSD ≤ 2.0% per USP <905>",
        "Tablet hardness uniformity: 20 tablets, RSD ≤ 5%",
        "Tablet friability: ≤ 1.0% weight loss per USP <1216>",
        "Content uniformity of blend: RSD ≤ 2% — confirms feeder performance",
        "Dissolution profile (release): ≥ 80% release at defined time point (product-specific)",
        "Process capability: Cpk ≥ 1.33 for tablet weight and hardness over 3 batches",
        "Throughput verification: rated output (tablets/hour) achievable without quality compromise",
        "Batch-to-batch reproducibility: 3 consecutive batches within specification",
    ],
    calibration_points=[
        "Pre-compression force transducer: 2, 5, 10, 15 kN — NIST-traceable load cell",
        "Main compression force transducer: 10, 20, 40, 60, 80 kN — NIST-traceable load cell",
        "Turret speed (RPM): 10, 20, 30, 40 RPM — calibrated tachometer",
        "In-process weight monitoring system: 50 mg, 100 mg, 200 mg, 500 mg — NIST weights",
        "Tablet weight rejection system: trigger accuracy at ±5% of target weight",
    ],
    safety_checks=[
        "Turret guard interlock: press stops within 0.5 s of guard opening",
        "Emergency stop button: accessible from both sides, tested at OQ",
        "Maximum compression force limiter: press auto-stops at overload (tested at 110% rated force)",
        "Punch pull-out / anti-rotation: verify punch retention mechanism integrity",
        "Dust explosion risk assessment: dust extraction and no ignition sources if combustible powder",
        "Lockout/tagout procedure documented for maintenance entry",
        "No operators reaching into turret area during operation (guarding verified)",
    ],
    documentation_checklist=[
        "Vendor factory acceptance test (FAT) report",
        "Punch and die certificate of conformance (dimensional, material, hardness)",
        "Force transducer calibration certificates",
        "HMI/PLC software validation report (CSV) and audit trail configuration",
        "Cleaning validation / cleaning SOP for press",
        "Instrument logbook (calibration, PM, punch/die changes, deviations)",
        "Product-specific compression recipe records",
        "Approved BMR sections for tablet compression process",
        "Preventive Maintenance SOP (punch/die inspection, lubrication schedule)",
        "Training records for all press operators and maintenance technicians",
    ],
    standard_acceptance_criteria=[
        "Turret speed accuracy: ±2% of set value",
        "Compression force accuracy: ±2% of set value",
        "Tablet weight RSD: ≤ 2.0% (20 tablets during OQ/PQ)",
        "Tablet hardness RSD: ≤ 5%",
        "Tablet friability: ≤ 1.0%",
        "Dissolution: product-specific (typically ≥ 80% at 30 min for IR tablets)",
        "Weight rejection system: 100% rejection of tablets outside ±5% of target weight",
        "Process capability: Cpk ≥ 1.33 for CQAs over 3 validation batches",
        "Interlock response: press stop within 0.5 s of guard opening",
    ],
    common_deviations=[
        "Tablet capping or lamination due to entrapped air — adjust pre-compression force",
        "Weight RSD > 2% due to powder flow issues — investigate feed frame speed and die fill",
        "Punch tip wear causing embossing defects — implement punch inspection SOP",
        "Sticking / filming on punch tip — formulation adjustment or punch coating",
        "Force transducer drift — enforce daily zero/span check before production",
        "Dust extraction blockage causing powder spill — check filter and clean per PM schedule",
        "Recipe version control gap — audit trail must capture recipe changes and approvals",
    ],
))


# ─── Capsule Filling Machine ──────────────────────────────────────────────────

_register(EquipmentProfile(
    name="CAPSULE FILLING MACHINE",
    aliases=["capsule filler", "capsule filling", "hard gelatin capsule filler",
             "hpmc capsule filler", "automatic capsule filler", "semi-automatic capsule filler",
             "capsule plugger", "encapsulator"],
    description=(
        "A Capsule Filling Machine fills hard gelatin (HPMC) capsule shells with powder, "
        "granules, pellets, tablets, or semisolids to produce oral capsule dosage forms. "
        "Intermittent motion (MG2, Bosch, IMA) and continuous motion machines fill at "
        "5,000–150,000 capsules/hour. Critical parameters: fill weight, fill weight variation, "
        "and capsule lock force. Governed by 21 CFR Part 211 and EU GMP."
    ),
    applicable_regulations=[
        "21 CFR Part 211.65 — Equipment construction",
        "21 CFR Part 211.68 — Automatic, mechanical, electronic equipment",
        "EU GMP Chapter 3 — Premises and Equipment",
        "EU GMP Annex 15 — Qualification and Validation",
        "ICH Q8(R2) — Pharmaceutical Development",
        "USP <1> — Injections (hard capsule reference for content uniformity)",
        "ICH Q10 — Pharmaceutical Quality System",
        "Schedule M — GMP for Pharmaceuticals (India)",
    ],
    required_utilities=[
        "Electrical: 380–415 V, 3-phase, 50 Hz; control panel 220–240 V, 50 Hz",
        "Compressed air: clean, dry, oil-free, 6–8 bar for capsule transport, vacuum, and rejection",
        "Vacuum: 50–80 mbar for capsule separation (may be integrated or external vacuum pump)",
        "Dust extraction: local exhaust ventilation at filling station (powder containment)",
        "Cleanroom: Grade D or controlled environment, 20–25°C, 40–55% RH (critical for gelatin)",
        "Nitrogen purging: for oxygen-sensitive formulations (optional)",
    ],
    critical_components=[
        "Capsule hopper and rectifier (orientation, separation of body and cap)",
        "Dosing disc / dosing system: powder dosator, tamping pin, or auger fill",
        "Fill weight monitoring system (in-process check weigher)",
        "Closing station (cap placement and locking mechanism)",
        "Vacuum pump system for capsule handling",
        "Ejection station and conveyor to polisher",
        "Reject system (weight-OOT capsule rejection chute)",
        "HMI / PLC with recipe management and audit trail",
        "Capsule polisher (typically inline)",
        "Metal detector (typically downstream of filler)",
    ],
    iq_checklist=[
        "Verify capsule filler model, filling principle (dosator/tamping), and capacity against URS/PO",
        "Confirm capsule size compatibility: size 000, 00, 0, 1, 2, 3, 4, 5 tooling available",
        "Verify product-contact materials: 316L SS, food-grade elastomers, PTFE dosators",
        "Check vacuum system installation, pump type, vacuum level at filling station",
        "Confirm compressed air quality: oil-free, particle-filtered (ISO 8573-1 Class 1.4.1)",
        "Verify HMI software version, recipe management, and audit trail configuration",
        "Check in-process checkweigher installation, load cell range, and calibration status",
        "Confirm dust extraction flow rate ≥ 0.5 m/s at fill station",
        "Verify safety guards, interlock switches, and emergency stop",
        "Confirm cleaning SOP compatibility: disassembly without tools required",
        "Register instrument in asset management system with unique equipment ID",
    ],
    oq_tests=[
        "Fill speed accuracy: set vs. actual capsules/hour ±5% at low, medium, and high speed",
        "Fill weight accuracy: target fill weight ±3% at all speed settings",
        "Fill weight variation: 10 capsules at each of 3 speeds — RSD ≤ 3%",
        "Vacuum level stability: ±5 mbar variation at capsule separation station over 10 min",
        "Capsule lock force (closing): no open or deformed capsules in 100-capsule check",
        "Rejection system: spiked under/over-weight capsules 100% rejected",
        "Dosator penetration depth / tamping force reproducibility: ±2% across all stations",
        "Capsule orientation accuracy: ≤ 0.5% inverted / wrongly oriented capsules in 100",
        "Audit trail: all parameter changes logged with user, timestamp, old/new values",
        "Interlock: machine stops when any guard is opened — verified for each guard",
    ],
    pq_tests=[
        "Fill weight uniformity over full batch: RSD ≤ 2.0% (10 capsules per 30-minute interval)",
        "Content uniformity: meets USP <905> / EP 2.9.40 (AV ≤ 15)",
        "Dissolution of filled capsules: product-specific acceptance criteria",
        "Throughput at rated speed: output meets URS, capsule quality maintained",
        "Batch-to-batch reproducibility: 3 consecutive batches within fill weight specification",
        "Process capability: Cpk ≥ 1.33 for fill weight",
        "Capsule appearance: ≤ 0.5% cosmetic defects (dented, cracked, spotted)",
    ],
    calibration_points=[
        "In-process checkweigher load cell: 100, 200, 300, 500 mg — NIST-traceable weights",
        "Rejection system trigger: at -5% and +5% of target fill weight",
        "Fill speed (capsules/hour): manual count vs. HMI display at 3 speeds",
        "Vacuum gauge: 0, 30, 60, 80 mbar — calibrated reference gauge",
        "Tamping force (if applicable): calibrated load cell at 50, 100, 150 N",
    ],
    safety_checks=[
        "All guards interlocked: machine stops within 0.5 s of guard opening",
        "Emergency stop accessible from both sides of machine",
        "Dust explosion assessment: compressed air purging prevents dust cloud formation",
        "Lockout/tagout procedure for format change and cleaning",
        "Gelatin allergy alert: PPE (gloves, mask) for operators handling capsule shells",
        "No open flame or static discharge near dry powder filling station",
    ],
    documentation_checklist=[
        "Vendor FAT report and installation certificate",
        "Tooling (dosator, tamping pin) material and dimensional certificates",
        "In-process checkweigher calibration certificate",
        "HMI/PLC software validation report and audit trail configuration",
        "Cleaning validation / cleaning SOP",
        "Product recipe records for each capsule size and formulation",
        "Instrument logbook (calibration, PM, tooling changes, deviations)",
        "Approved BMR sections for capsule filling",
        "Training records for operators and technicians",
        "Preventive Maintenance SOP",
    ],
    standard_acceptance_criteria=[
        "Fill weight accuracy: target ±3%",
        "Fill weight RSD: ≤ 2.0% (10 capsules per time interval)",
        "Content uniformity: AV ≤ 15 (USP <905>)",
        "Rejection efficiency: 100% rejection of out-of-weight capsules",
        "Capsule defect rate: ≤ 0.5% cosmetic defects",
        "Process capability: Cpk ≥ 1.33 for fill weight",
        "Dissolution: product-specific specification",
    ],
    common_deviations=[
        "Fill weight variation due to powder flow inconsistency — review granule PSD and flow indices",
        "Capsule cap not locking (telescoping): check closing force and humidity (gelatin brittleness)",
        "Dosator clogging with sticky powder — formulation review; reduce fill compression force",
        "In-process checkweigher rejection rate > 1% — investigate fill mechanism and powder bridge",
        "Capsule body inversion at rectifier — adjust rectifier brush speed and vacuum level",
        "Audit trail not capturing recipe changes — enforce user login and recipe lock policy",
    ],
))
