"""Processing equipment: Tablet Coater, Fluid Bed Dryer, Rapid Mixer Granulator, Bin Blender."""

from pharmagpt.equipment import EquipmentProfile, _register

# ─── Tablet Coater ────────────────────────────────────────────────────────────

_register(EquipmentProfile(
    name="TABLET COATER",
    aliases=["coating pan", "tablet coating machine", "film coater", "aqueous coater",
             "organic solvent coater", "perforated pan coater", "accela-cota", "hi-coater",
             "sugar coater", "enteric coater", "film coating pan"],
    description=(
        "A Tablet Coater (Perforated Pan Coater) applies aqueous or solvent-based film coatings "
        "to tablet cores in a rotating perforated drum with inlet and exhaust air systems. "
        "Critical process parameters: inlet air temperature, exhaust air temperature, pan speed, "
        "spray rate, atomisation air pressure, and product bed temperature. "
        "Coating ensures taste masking, moisture protection, modified release, or cosmetic appearance."
    ),
    applicable_regulations=[
        "21 CFR Part 211.65 — Equipment construction",
        "21 CFR Part 211.68 — Automatic, mechanical, electronic equipment",
        "EU GMP Chapter 3 — Premises and Equipment",
        "EU GMP Annex 15 — Qualification and Validation",
        "ICH Q8(R2) — Pharmaceutical Development (coating as critical process step)",
        "ICH Q10 — Pharmaceutical Quality System",
        "NFPA 33 / IEC 60079 — Explosion protection (solvent-based coating)",
        "Schedule M — GMP for Pharmaceuticals (India)",
    ],
    required_utilities=[
        "Electrical: 380–415 V, 3-phase, 50 Hz; control panel 220–240 V",
        "Compressed air: clean, dry, oil-free, 6–8 bar (atomisation and pan inlet)",
        "Heating: steam or electric air heater for inlet air (60–80°C typical)",
        "Exhaust ducting: HEPA-filtered exhaust, explosion-proof if solvent coating",
        "Purified water or WFI: for aqueous coating solution preparation",
        "Solvent-rated zone: ATEX / IECEx rated equipment if organic solvent used",
        "Cleanroom: Grade D or controlled, 20–25°C, 40–55% RH",
    ],
    critical_components=[
        "Perforated pan drum (316L SS, pan angle 0–15°, peristaltic baffles)",
        "Pan drive motor with speed controller (1–15 RPM typical)",
        "Spray gun assembly (binary or airless nozzles; 1–6 guns per pan size)",
        "Peristaltic pump for coating solution delivery",
        "Inlet air handling unit (HEPA-filtered, heated, humidity-controlled)",
        "Exhaust fan with HEPA filter and, if solvent, scrubber or condenser",
        "Product bed temperature sensor (inlet, exhaust, optional IR probe)",
        "HMI / PLC with recipe management and audit trail",
        "Bag filter / cyclone for fine particle recovery",
        "Solvent detection system (if organic solvent)",
    ],
    iq_checklist=[
        "Verify coater model, pan capacity, and pan perforation specification against URS/PO",
        "Confirm pan material: 316L SS, surface finish Ra ≤ 0.8 µm, no dead-legs",
        "Verify spray gun model, nozzle size, and atomisation pressure range",
        "Check inlet air handling unit: HEPA filter certificate, heater capacity, humidity control",
        "Confirm exhaust fan capacity and HEPA/scrubber installation",
        "Verify all temperature sensors (inlet, exhaust, product bed) calibration status",
        "Check compressed air quality: oil-free filter (ISO 8573-1 Class 1.4.1)",
        "Confirm pan drive motor speed range and tachometer installation",
        "Verify peristaltic pump: tubing material (silicone FDA-grade), flow rate range",
        "For solvent coating: verify ATEX classification of all electrical components; solvent alarm installed",
        "Confirm HMI software version, recipe management, and audit trail activation",
        "Register instrument in asset management system",
    ],
    oq_tests=[
        "Pan speed accuracy: 2, 5, 10, 15 RPM — tachometer ±2%",
        "Inlet air temperature accuracy: 40°C, 60°C, 80°C — NIST-traceable sensor ±1°C",
        "Exhaust air temperature accuracy: 35°C, 45°C, 55°C — ±1°C",
        "Spray rate accuracy: 10, 20, 50 g/min — gravimetric collection ±5%",
        "Atomisation air pressure accuracy: 1, 2, 3 bar — calibrated gauge ±0.1 bar",
        "Inlet air volume flow: set vs. measured ±10% (calibrated anemometer)",
        "Exhaust negative pressure: pan at set negative pressure during operation ±5 Pa",
        "Product bed temperature stability: set vs. measured ±2°C over 30-minute hold",
        "Pan perforation coverage: inspect for blocked perforations (visual + airflow check)",
        "Solvent detector alarm (if applicable): simulated vapour at 10% LEL — alarm triggers",
        "Audit trail: all recipe parameter changes logged with user, timestamp, old/new values",
    ],
    pq_tests=[
        "Film weight gain uniformity: ≤ 3% RSD across 20 tablets from multiple pan positions",
        "Coating appearance: ≤ 0.5% cracked, chipped, or twinned tablets in batch AQL",
        "Coating thickness uniformity (SEM or weight gain): RSD ≤ 5%",
        "Modified release coating: dissolution profile meets specification (if enteric/sustained release)",
        "Moisture content: coated tablet moisture ≤ specified limit (Karl Fischer or LOD)",
        "Colour uniformity: dE ≤ 3 (CIE Lab) across batch and batch-to-batch",
        "Batch-to-batch reproducibility: 3 consecutive batches meeting all CQAs",
        "Process capability: Cpk ≥ 1.33 for weight gain",
    ],
    calibration_points=[
        "Inlet air temperature: 40°C, 60°C, 80°C — NIST-traceable PT100 reference",
        "Exhaust air temperature: 35°C, 45°C, 55°C",
        "Product bed temperature (IR probe): 30°C, 40°C, 50°C — blackbody reference",
        "Pan speed (RPM): 2, 5, 10, 15 — contact tachometer",
        "Spray rate: gravimetric collection at 3 flow settings",
        "Atomisation air pressure: 1, 2, 3 bar — calibrated reference gauge",
        "Peristaltic pump flow rate: gravimetric at 10, 20, 50 g/min",
    ],
    safety_checks=[
        "Solvent vapour alarm: set at ≤ 10% LEL, tested before each solvent coating run",
        "ATEX-rated equipment: all electrical components rated for Zone 2 (solvent coating)",
        "Explosion-proof exhaust fan and ductwork (solvent coating)",
        "Interlocked pan access door: pan cannot rotate while door is fully open",
        "Emergency stop accessible from both sides of machine",
        "Lockout/tagout procedure for spray gun cleaning and pan access",
        "Hot surface warning: inlet air plenum and heating element accessible only after cooling",
    ],
    documentation_checklist=[
        "Vendor FAT report and site installation certificate",
        "Inlet air HEPA filter integrity test certificate",
        "Temperature sensor calibration certificates (all probes)",
        "Solvent vapour alarm calibration certificate (if applicable)",
        "Peristaltic pump tubing FDA compliance certificate",
        "HMI/PLC software validation report and audit trail configuration",
        "Cleaning validation SOP and cleaning validation report",
        "Product-specific coating recipe records",
        "Instrument logbook (calibration, PM, nozzle changes, deviations)",
        "Training records for operators and maintenance technicians",
        "Preventive Maintenance SOP (nozzle cleaning, filter replacement, pump tube schedule)",
    ],
    standard_acceptance_criteria=[
        "Pan speed: ±2% of set value",
        "Inlet air temperature: ±1°C",
        "Exhaust air temperature: ±1°C",
        "Spray rate: ±5% of set value",
        "Atomisation air pressure: ±0.1 bar",
        "Film weight gain RSD: ≤ 3%",
        "Coating appearance defects: ≤ 0.5%",
        "Process capability: Cpk ≥ 1.33 for weight gain",
        "Dissolution (modified release): meets product-specific specification",
    ],
    common_deviations=[
        "Tablet twinning / sticking — reduce spray rate and increase pan speed; review pan load",
        "Chipping / logo bridging — reduce atomisation pressure; inspect tablet core friability",
        "Colour mottling — improve spray gun overlap and inlet air distribution baffles",
        "Film weight gain non-uniformity — check for gun clogging; verify all guns spray uniformly",
        "Exhaust HEPA filter blinding — schedule replacement per differential pressure alarm",
        "Solvent alarm nuisance trips — verify calibration and set point accuracy",
    ],
))


# ─── Fluid Bed Dryer ──────────────────────────────────────────────────────────

_register(EquipmentProfile(
    name="FLUID BED DRYER",
    aliases=["fbd", "fluid bed dryer", "fluidised bed dryer", "fluidized bed dryer",
             "fluid bed processor", "fbp", "top spray fbd", "wurster coater",
             "fluid bed granulator dryer", "fluid bed equipment"],
    description=(
        "A Fluid Bed Dryer (FBD) dries wet granules or powders by suspending particles "
        "in a stream of heated, filtered air. Also configured for granulation (top-spray) "
        "or pellet coating (Wurster insert). Critical parameters: inlet air temperature, "
        "product temperature, exhaust air temperature, airflow (CFM), and end-point moisture. "
        "Widely used in granulation suites and requires earthing for static discharge control."
    ),
    applicable_regulations=[
        "21 CFR Part 211.65 — Equipment construction",
        "21 CFR Part 211.68 — Automatic, mechanical, electronic equipment",
        "EU GMP Chapter 3 — Premises and Equipment",
        "EU GMP Annex 15 — Qualification and Validation",
        "ICH Q8(R2) — Pharmaceutical Development",
        "NFPA 68 / IEC 60079 — Explosion protection (organic solvent FBD)",
        "ISPE Baseline Guide Vol. 5 — Commissioning and Qualification",
        "Schedule M — GMP for Pharmaceuticals (India)",
    ],
    required_utilities=[
        "Electrical: 380–415 V, 3-phase, 50 Hz; control panel 220–240 V",
        "Compressed air: clean, dry, oil-free, 6–8 bar (bag filter shaking / pulse jet)",
        "Steam or electric heat: inlet air heater 60–100°C",
        "Exhaust ducting: HEPA-filtered exhaust, explosion-proof for solvent-containing products",
        "Earth bonding: product bowl and expansion chamber must be continuously earthed (static discharge)",
        "Cleanroom: Grade D, 20–25°C, 40–55% RH (humidity affects drying curve)",
    ],
    critical_components=[
        "Product bowl / container (316L SS, mirror-polished, with product mesh screen)",
        "Inlet air plenum and air distribution plate",
        "Inlet air handling unit: HEPA filter, pre-filter, heater, and humidity sensor",
        "Finger bag filter / cartridge filter assembly (PTFE-coated) with shake mechanism",
        "Exhaust fan (explosion-proof if solvent) with exhaust HEPA filter",
        "Temperature sensors: inlet (T_in), product (T_product), exhaust (T_ex) — PT100",
        "Moisture end-point detection (NIR or exhaust dew point sensor)",
        "HMI / PLC with recipe management and audit trail",
        "Earth strap and continuity indicator for bowl and expansion chamber",
        "Pressure relief panel (explosion suppression for solvent or flammable products)",
    ],
    iq_checklist=[
        "Verify FBD model, bowl capacity, and airflow range (CFM/m³/h) against URS/PO",
        "Confirm bowl material: 316L SS, surface finish Ra ≤ 0.8 µm",
        "Verify product mesh screen: mesh size, material, and integrity",
        "Confirm inlet HEPA filter installation and certificate (DOP/PAO test)",
        "Check filter bag installation: no tears, correct material for product (PTFE antistatic)",
        "Verify earth bonding: bowl earth strap continuity indicator functional (< 1 Ω)",
        "Check all temperature probes (inlet, product, exhaust) calibration status",
        "Confirm compressed air filtration and pressure regulator",
        "Verify HMI software version, recipe management, and audit trail activation",
        "Check all access doors and interlocking: bowl cannot be removed while fan is running",
        "For solvent products: confirm ATEX classification of all electrical components",
        "Register instrument in asset management system with unique ID",
    ],
    oq_tests=[
        "Inlet air temperature accuracy: 40°C, 60°C, 80°C — calibrated PT100 reference ±1°C",
        "Exhaust air temperature accuracy: 30°C, 45°C, 60°C — ±1°C",
        "Product temperature sensor accuracy: 35°C, 45°C, 55°C — ±1°C",
        "Airflow (blower speed / flap position): set vs. measured CFM ±10% (anemometer)",
        "Differential pressure across bag filters: alarm at set ΔP (filter blinding test)",
        "Filter bag shake cycle: compressed air pressure ±0.5 bar and interval accuracy",
        "Earth strap continuity: ≤ 1 Ω during bowl installation and operation",
        "End-point moisture sensor (NIR/dew point): verified against reference LOD measurement ±0.5%",
        "Bowl locking interlock: fan cannot start unless bowl locked; bowl cannot be removed while fan runs",
        "Audit trail: all recipe changes logged with user, timestamp, old/new values",
    ],
    pq_tests=[
        "Moisture uniformity: sample from 3 bowl positions (top, middle, bottom) — LOD RSD ≤ 5%",
        "Drying curve reproducibility: moisture vs. time profiles from 3 batches overlay within ±5%",
        "End-point accuracy: LOD at auto-detected end-point within ±0.5% of specification",
        "Granule PSD: sieve analysis of dried granules meets specification",
        "Bulk density: post-drying bulk density meets specification",
        "Batch-to-batch reproducibility: 3 consecutive batches within LOD specification",
        "Process capability: Cpk ≥ 1.33 for LOD at end-point",
    ],
    calibration_points=[
        "Inlet air temperature: 40°C, 60°C, 80°C — NIST-traceable PT100 reference thermometer",
        "Product temperature: 35°C, 45°C, 55°C — verified against NIST reference",
        "Exhaust temperature: 30°C, 45°C, 60°C",
        "Airflow: measured vs. set CFM — calibrated anemometer or pitot tube",
        "NIR/dew point moisture sensor: calibrated against LOD (loss on drying) reference method",
        "Filter bag pressure differential gauge: calibrated reference gauge",
    ],
    safety_checks=[
        "Earth bonding continuity: verified before every batch; alarm on earth loss",
        "Explosion relief panel or suppression system: annual inspection",
        "Solvent vapour alarm (if solvent-containing granules): set at ≤ 10% LEL",
        "Blower interlock: bowl must be locked before fan starts; bowl cannot be removed while fan is running",
        "Thermal runaway: inlet air high-temperature alarm and cutoff tested",
        "Bag filter access door: must be closed and interlocked before start",
    ],
    documentation_checklist=[
        "Vendor FAT report and site installation certificate",
        "Inlet HEPA filter integrity test certificate",
        "Temperature sensor calibration certificates (all probes)",
        "NIR/dew point sensor calibration certificate",
        "Earth bond continuity records",
        "Explosion relief / suppression system inspection certificate (if applicable)",
        "HMI/PLC software validation report and audit trail configuration",
        "Cleaning validation SOP and validation report",
        "Product-specific drying recipe records",
        "Instrument logbook (calibration, PM, filter changes, deviations)",
        "Training records for operators and maintenance technicians",
    ],
    standard_acceptance_criteria=[
        "Inlet air temperature: ±1°C of set value",
        "Product temperature: ±1°C of set value",
        "Airflow: ±10% of set value",
        "Moisture end-point: within ±0.5% LOD of specification",
        "Moisture uniformity (3 bowl positions): RSD ≤ 5%",
        "Earth bond continuity: ≤ 1 Ω",
        "Filter ΔP alarm: triggers before product carryover occurs",
        "Process capability: Cpk ≥ 1.33 for LOD",
    ],
    common_deviations=[
        "Product carryover into bag filters due to excessive airflow — reduce blower speed",
        "Moisture non-uniformity across bowl — inspect air distribution plate for blockage",
        "Earth strap failure during operation — alarm system and visual check before each batch",
        "Filter bag tear — implement visual inspection of bags before each batch",
        "LOD end-point not reached at set exhaust temperature — investigate product load and ambient humidity",
        "Drying curve shift batch-to-batch — review inlet humidity variation and HVAC performance",
    ],
))


# ─── Rapid Mixer Granulator ───────────────────────────────────────────────────

_register(EquipmentProfile(
    name="RAPID MIXER GRANULATOR",
    aliases=["rmg", "high shear granulator", "high shear mixer granulator",
             "planetary mixer granulator", "vertical granulator", "mixer granulator",
             "diosna granulator", "collette gral"],
    description=(
        "A Rapid Mixer Granulator (RMG / High Shear Mixer Granulator) produces wet granules "
        "by mixing dry powder blend, adding binder solution, and chopping/agglomerating into "
        "granules in a jacketed bowl. Critical parameters: impeller speed, chopper speed, "
        "granulation time, binder addition rate, and product temperature. "
        "Granule properties (PSD, bulk density) directly impact downstream tablet compression quality."
    ),
    applicable_regulations=[
        "21 CFR Part 211.65 — Equipment construction",
        "21 CFR Part 211.68 — Automatic, mechanical, electronic equipment",
        "EU GMP Chapter 3 — Premises and Equipment",
        "EU GMP Annex 15 — Qualification and Validation",
        "ICH Q8(R2) — Pharmaceutical Development",
        "ICH Q10 — Pharmaceutical Quality System",
        "ISPE Baseline Guide Vol. 5 — Commissioning and Qualification",
        "Schedule M — GMP for Pharmaceuticals (India)",
    ],
    required_utilities=[
        "Electrical: 380–415 V, 3-phase, 50 Hz; impeller motor typically 15–90 kW",
        "Compressed air: 6–8 bar (bowl lifting, seals, chopper seal purge)",
        "Steam or chilled water: bowl jacket for temperature-controlled granulation",
        "Purified water or WFI: for binder solution preparation",
        "Exhaust ventilation: dust extraction at bowl lid and discharge",
        "Cleanroom: Grade D, 20–25°C, 40–55% RH",
    ],
    critical_components=[
        "Bowl (316L SS, mirror-polished, with tangential binder spray nozzle)",
        "Impeller (star or propeller type, bottom-driven) with speed controller (50–300 RPM)",
        "Chopper (side-mounted, 1000–3000 RPM) with speed controller",
        "Bowl jacket with inlet and outlet temperature sensors and flow control",
        "Impeller and chopper seal purge (compressed air or inert gas)",
        "Bowl lid with binder spray nozzle(s) and discharge port cover",
        "Power consumption / current monitoring for wet massing end-point detection",
        "HMI / PLC with recipe management and audit trail",
        "Discharge valve (bottom or side, gravity or compressed air actuated)",
    ],
    iq_checklist=[
        "Verify RMG model, bowl capacity, and impeller/chopper motor ratings against URS/PO",
        "Confirm bowl material: 316L SS, surface finish Ra ≤ 0.4 µm (mirror polish required)",
        "Verify impeller geometry (blade angle, number, clearance from bowl bottom ≤ 2 mm)",
        "Check chopper installation: speed range, guard, and interlock",
        "Confirm bowl jacket: connections for steam/chilled water, temperature sensor location",
        "Verify binder spray nozzle installation: nozzle type, spray angle, and flow range",
        "Check seal purge air supply and pressure regulator",
        "Confirm power consumption / current monitoring wiring and display",
        "Verify HMI software version, recipe management, and audit trail configuration",
        "Check all safety interlocks: impeller cannot run if bowl lid is open",
        "Register instrument in asset management system with unique ID",
    ],
    oq_tests=[
        "Impeller speed accuracy: 100, 200, 300 RPM — calibrated tachometer ±2%",
        "Chopper speed accuracy: 1000, 1500, 3000 RPM — calibrated tachometer ±2%",
        "Bowl jacket temperature accuracy: 20°C, 30°C, 40°C — NIST-traceable PT100 ±1°C",
        "Binder spray rate: 50, 100, 200 g/min — gravimetric ±5%",
        "Power consumption display: verified against reference ammeter ±2%",
        "Impeller-to-bowl bottom clearance: ≤ 2 mm (feeler gauge measurement at 4 positions)",
        "Bowl lid interlock: impeller cannot start with lid open; lid cannot be opened while impeller running",
        "Discharge valve actuation: complete open and close within 5 seconds",
        "Compressed air seal purge pressure: ±0.5 bar of set value",
        "Audit trail: all recipe changes logged",
    ],
    pq_tests=[
        "Granule PSD: sieve analysis meets specification (D50, D90) across 3 batches",
        "Bulk density and tapped density: meets specification, Carr's Index ≤ 25%",
        "Moisture content (LOD): granule moisture within specification (for FBD compatibility)",
        "Granule yield: ≥ 98% mass balance after granulation",
        "Granule content uniformity: API assay RSD ≤ 2% across 5 samples",
        "Batch-to-batch reproducibility: 3 consecutive batches within all CQA specifications",
        "Power consumption end-point: identify current peak as granulation end-point marker",
        "Process capability: Cpk ≥ 1.33 for granule D50",
    ],
    calibration_points=[
        "Impeller speed: 100, 200, 300 RPM — calibrated contact tachometer",
        "Chopper speed: 1000, 1500, 3000 RPM",
        "Bowl jacket temperature: 20°C, 30°C, 40°C — NIST PT100 reference",
        "Binder spray pump flow rate: 50, 100, 200 g/min — gravimetric",
        "Power/current monitor: verified against reference ammeter at 3 load levels",
        "Impeller-to-bowl clearance: feeler gauge (calibrated) at 4 quadrant positions",
    ],
    safety_checks=[
        "Bowl lid interlock: impeller and chopper cannot run if lid is open — tested at OQ",
        "Impeller overload protection: motor thermal cutoff tested",
        "Chopper guard: no access to chopper blades during operation",
        "Discharge valve interlock: cannot open while impeller is running",
        "Emergency stop accessible from both sides",
        "Lockout/tagout procedure for impeller and chopper blade change",
        "Dust mask and chemical goggles: mandatory for dry mixing phase",
    ],
    documentation_checklist=[
        "Vendor FAT report and site installation certificate",
        "Impeller and chopper speed calibration certificates",
        "Bowl jacket temperature calibration certificates",
        "Binder spray pump calibration certificate",
        "Impeller blade dimensional certificate (blade angle, clearance spec)",
        "HMI/PLC software validation report and audit trail configuration",
        "Cleaning validation SOP and validation report",
        "Product-specific granulation recipe records",
        "Instrument logbook (calibration, PM, blade changes, deviations)",
        "Training records for operators and maintenance technicians",
    ],
    standard_acceptance_criteria=[
        "Impeller speed: ±2% of set value",
        "Chopper speed: ±2% of set value",
        "Bowl jacket temperature: ±1°C",
        "Binder spray rate: ±5%",
        "Impeller-to-bowl clearance: ≤ 2 mm",
        "Granule D50: within specification ± product-specific tolerance",
        "Granule content uniformity: RSD ≤ 2%",
        "Process capability: Cpk ≥ 1.33 for granule D50",
    ],
    common_deviations=[
        "Over-granulation (wet mass) causing dense granules — reduce binder volume or spray rate",
        "Under-granulation — increase mixing time or binder concentration",
        "API de-mixing during dry mixing — ensure pre-mix homogeneity before binder addition",
        "Impeller blade wear increasing bottom clearance — measure and replace blade per PM SOP",
        "Chopper seal failure causing powder leak — inspect seal daily; replace per PM schedule",
        "Power consumption end-point repeatability poor — investigate binder concentration consistency",
    ],
))


# ─── Bin Blender ──────────────────────────────────────────────────────────────

_register(EquipmentProfile(
    name="BIN BLENDER",
    aliases=["ibc blender", "bin blending", "ibc mixer", "intermediate bulk container blender",
             "tumble blender", "container blender", "bin blending system",
             "octagonal blender", "v-blender"],
    description=(
        "A Bin Blender (IBC Blender) achieves powder blending by rotating an Intermediate Bulk "
        "Container (IBC / drum / bin) about a horizontal axis (tumble blending). Advantages: "
        "closed-system blending without powder transfer, reduced cross-contamination risk, "
        "and direct bin-to-press product delivery. Critical parameters: blend speed (RPM), "
        "blend time (revolutions or minutes), bin fill level, and blend uniformity (RSD ≤ 3%)."
    ),
    applicable_regulations=[
        "21 CFR Part 211.68 — Automatic, mechanical, electronic equipment",
        "21 CFR Part 211.100 — Written procedures; deviations",
        "EU GMP Chapter 3 — Premises and Equipment",
        "EU GMP Annex 15 — Qualification and Validation",
        "ICH Q8(R2) — Pharmaceutical Development",
        "ICH Q10 — Pharmaceutical Quality System",
        "ISPE Baseline Guide Vol. 5 — Commissioning and Qualification",
        "Schedule M — GMP for Pharmaceuticals (India)",
    ],
    required_utilities=[
        "Electrical: 380–415 V, 3-phase, 50 Hz (drive motor); control panel 220–240 V",
        "Compressed air: 6 bar (bin locking, bin identification sensor)",
        "Stable floor installation: bin blenders have dynamic load — structural assessment required",
        "Cleanroom: Grade D; dust containment at bin ports during loading/unloading",
    ],
    critical_components=[
        "Drive unit with coupling system (drives bin at set RPM, typically 4–20 RPM)",
        "Revolution counter / timer for blend control",
        "Bin locking / clamping mechanism (ensures bin is secured before rotation)",
        "Bin ID reader (barcode or RFID) for batch traceability",
        "Anti-static earthing strap for bin (continuous earthing during rotation)",
        "HMI / PLC with recipe management (RPM, revolutions, time) and audit trail",
        "IBC bin: 316L SS, octagonal or cylindrical, with butterfly valve and sealed ports",
        "Inverter / VFD for smooth speed ramp-up (prevents powder segregation at start)",
    ],
    iq_checklist=[
        "Verify bin blender model, drive capacity (bin volume range), and speed range against URS/PO",
        "Confirm bin (IBC) size compatibility with blender coupling system",
        "Verify bin material: 316L SS, surface finish Ra ≤ 0.8 µm, butterfly valve type",
        "Check bin locking / clamping mechanism: secure engagement before start interlock",
        "Confirm earth strap connection point on blender and bin",
        "Verify bin ID reader installation (barcode scanner or RFID)",
        "Check VFD / inverter installation and ramp-up profile settings",
        "Confirm HMI software version, recipe management, and audit trail configuration",
        "Verify revolution counter and timer calibration",
        "Register instrument in asset management system; confirm bin IBC is separately tagged",
    ],
    oq_tests=[
        "Drive speed accuracy: 5, 10, 15, 20 RPM — calibrated tachometer ±2%",
        "Revolution count accuracy: 50, 100, 200 revolutions — counter vs. manual count ±2",
        "Blend time accuracy: timer ±30 s over 30-minute blend",
        "Bin locking interlock: blender cannot start if bin is not locked — tested with unlocked bin",
        "Earth strap continuity during rotation: ≤ 1 Ω (continuous monitoring, if fitted)",
        "Bin ID reader: correctly reads bin barcode/RFID for 5 different bins",
        "VFD ramp-up: smooth speed increase from 0 to set RPM, no bin jerk",
        "Emergency stop: blender stops within 5 seconds of E-stop activation",
        "Audit trail: all recipe parameter changes logged with user, timestamp, old/new values",
    ],
    pq_tests=[
        "Blend uniformity (10 samples per blend): RSD ≤ 3% for API content (ASTM E2591)",
        "Blend uniformity at low fill level (50% rated capacity): RSD ≤ 3%",
        "Blend uniformity at high fill level (80% rated capacity): RSD ≤ 3%",
        "Lubrication blend (post-lubrication add): lubricant distribution RSD ≤ 3%",
        "Over-blending study: blend uniformity at 2× optimal revolutions — confirm no de-mixing",
        "Batch-to-batch reproducibility: 3 consecutive batches within specification",
        "Process capability: Cpk ≥ 1.33 for API content uniformity in blend",
        "Thief probe verification: confirm sampling tool does not cause API enrichment at sample point",
    ],
    calibration_points=[
        "Drive speed: 5, 10, 15, 20 RPM — calibrated contact tachometer",
        "Revolution counter: 50, 100, 200 — manual count verification",
        "Timer: 30 min duration — calibrated stopwatch",
        "Earth strap continuity meter: 0, 0.5, 1, 2 Ω — resistance decade box",
    ],
    safety_checks=[
        "Bin locking interlock: 100% prevention of rotation with unlocked bin",
        "Earth strap: verified before every batch; alarm or warning indicator for continuity loss",
        "Rotating machinery exclusion zone: no operators within 1 m of rotating bin",
        "Emergency stop accessible from both blender sides",
        "Maximum fill level enforced: do not exceed 80% bin capacity (risk of segregation and overflow)",
        "Lockout/tagout procedure for bin coupling and bin port maintenance",
    ],
    documentation_checklist=[
        "Vendor FAT report and site installation certificate",
        "IBC bin qualification report (dimensions, surface finish, butterfly valve test)",
        "Revolution counter and timer calibration certificate",
        "Earth strap continuity meter calibration certificate",
        "HMI/PLC software validation report and audit trail configuration",
        "Blend uniformity study reports (PQ — all batch sizes)",
        "Thief probe qualification study",
        "Cleaning validation SOP and validation report",
        "Product-specific blend recipe records",
        "Instrument logbook (calibration, PM, deviations)",
        "Training records for all operators and maintenance technicians",
    ],
    standard_acceptance_criteria=[
        "Drive speed: ±2% of set value",
        "Revolution count: ±2 revolutions",
        "Blend uniformity RSD: ≤ 3% (API content, 10 samples)",
        "Lubrication blend uniformity RSD: ≤ 3%",
        "Bin locking interlock: 100% — no rotation without locked bin",
        "Earth strap continuity: ≤ 1 Ω",
        "Process capability: Cpk ≥ 1.33 for API blend uniformity",
    ],
    common_deviations=[
        "Blend uniformity RSD > 3% due to over-blending causing segregation — establish optimal RPM",
        "Earth strap failure during rotation — alarms not fitted; add continuity monitoring",
        "Bin locking interlock bypass during format change — enforce MO/logbook procedure",
        "Thief sampling artefact introducing high RSD — validate thief probe design for product",
        "API hot-spot at bin valve — sample from valve port and compare to body samples",
        "Revolution counter malfunction — backup timer-based control as safety net",
    ],
))
