"""Sterilization equipment: Autoclave, VHP Generator."""

from pharmagpt.equipment import EquipmentProfile, _register

# ─── Autoclave ────────────────────────────────────────────────────────────────

_register(EquipmentProfile(
    name="AUTOCLAVE",
    aliases=["steam sterilizer", "autoclave sterilizer", "steam autoclave",
             "porous load autoclave", "liquid load autoclave", "retort sterilizer",
             "saturated steam sterilizer", "moist heat sterilizer"],
    description=(
        "An Autoclave (Steam Sterilizer) achieves sterilization using saturated steam under "
        "pressure, typically at 121°C / 15 psi (porous load) or 134°C / 30 psi (flash cycles). "
        "Used for sterilizing equipment, media, gowning, and heat-stable products. "
        "Qualified per HTM 01-01, EN 285, ISO 17665, and EU GMP Annex 1. "
        "Validation includes heat distribution, heat penetration, and biological indicator studies."
    ),
    applicable_regulations=[
        "EU GMP Annex 1 — Manufacture of Sterile Medicinal Products (2022)",
        "ISO 17665-1 — Sterilization of health-care products: Moist heat",
        "EN 285 — Sterilization: Large steam sterilizers",
        "HTM 01-01 — Processing in Sterile Services (UK)",
        "21 CFR Part 211.67 — Equipment cleaning and maintenance",
        "21 CFR Part 211.113 — Control of microbiological contamination",
        "USP <1229.1> — Steam Sterilization by Direct Contact",
        "PDA Technical Report 1 — Validation of Moist Heat Sterilization Processes",
        "ISPE Baseline Guide Vol. 5 — Commissioning and Qualification",
    ],
    required_utilities=[
        "Steam supply: plant steam (saturated, dry, >98% quality) at 3–5 bar, dedicated line",
        "Compressed air: clean, dry, oil-free, 6–8 bar for door seal and valve actuation",
        "Cooling water: potable or purified, 1–3 bar, 15–25°C inlet temperature",
        "Electrical: 380–415 V, 3-phase, 50 Hz; control panel: 220–240 V, 50 Hz",
        "Floor drain: adequate capacity for condensate discharge",
        "Exhaust ventilation for steam discharge",
        "Clean steam (WFI-quality) if product contact or clean room application",
    ],
    critical_components=[
        "Chamber (grade 316L stainless steel, with ASME/PED certification)",
        "Door(s) with interlocking safety mechanism (single or double door)",
        "Door gasket / seal (silicone or EPDM, replaceable)",
        "Steam jacket for temperature uniformity",
        "Air removal system (pre-vacuum or downward displacement with air detector)",
        "Temperature sensors (RTDs/thermocouples, ≥2 per chamber — NIST traceable)",
        "Pressure transducer (chamber and jacket — NIST traceable)",
        "Safety relief valve (ASME-certified, tested annually)",
        "Programmable Logic Controller (PLC) with batch record generation",
        "Printer / data logger for cycle documentation",
        "Biological Indicator (BI) test port / carrier system",
    ],
    iq_checklist=[
        "Verify chamber material certificate (316L SS, surface finish Ra ≤ 0.5 µm for clean steam)",
        "Confirm ASME Section VIII / PED pressure vessel certification and stamping",
        "Verify door interlock safety system (cannot open under pressure > 0.1 bar)",
        "Check all utility connections: steam, compressed air, cooling water, drain, electrical",
        "Confirm steam quality test: dryness fraction ≥ 0.95, non-condensable gases ≤ 3.5%",
        "Verify temperature probe (RTD/TC) positions and calibration certificates (NIST traceable)",
        "Confirm pressure transducer calibration certificate",
        "Check safety relief valve certification and set pressure",
        "Verify PLC software version and cycle programme (121°C, 134°C, etc.) configuration",
        "Confirm batch record / printer output includes all required data fields",
        "Verify all gaskets/seals material specification and installation",
        "Check condensate drain and trap function: no steam bypass",
        "Confirm equipment registration in asset management system (pressure vessel register)",
        "Verify air detector / Bowie-Dick test port installation",
    ],
    oq_tests=[
        "Temperature distribution (empty chamber): ≥ 10 thermocouples, ΔT ≤ 1.0°C at equilibration",
        "Heat distribution uniformity: all positions 121°C ± 1°C throughout hold phase",
        "Temperature penetration (loaded chamber): worst-case load — all positions meet Fo requirement",
        "Cycle time accuracy: timer starts only after equilibration; hold phase ±30 seconds",
        "Pressure accuracy: chamber pressure ≤ ±0.1 bar of set point at equilibration",
        "Air removal test (Bowie-Dick or vacuum leak test): test pack fully penetrated, no cold spot",
        "Vacuum leak rate test: ≤ 1.3 mbar/min after evacuation (porous load)",
        "Drain temperature: ≥ 121°C at drain thermocouple during hold phase",
        "PLC batch record accuracy: all data fields populated, time-stamped, and printed",
        "Door interlock test: attempt to open door during pressurised phase — must prevent opening",
        "Safety relief valve set-pressure verification (mechanical test with calibrated gauge)",
        "Fail-safe test: simulate loss of steam — PLC aborts cycle and generates alarm",
    ],
    pq_tests=[
        "Heat penetration study: product/media in representative load, all positions Fo ≥ 12 min",
        "Biological Indicator study: Geobacillus stearothermophilus BI (D₁₂₁ ≥ 1.5 min) — no growth after cycle",
        "Bioburden + Fo approach (parametric release): challenge with BI + bioburden data",
        "Worst-case load study: maximum load, full container density — meets Fo requirement",
        "Cycle reproducibility: ≥ 3 consecutive cycles meeting all acceptance criteria",
        "Media fill simulation: sterility of processed media confirmed (USP <71> sterility test)",
        "Residual moisture / dryness: wrapped items emerge dry (porous load cycles)",
    ],
    calibration_points=[
        "Temperature sensors (all chamber RTDs/TCs): 100°C, 121°C, 134°C — NIST traceable furnace",
        "Pressure transducer: 0, 1, 2, 3 bar — NIST traceable deadweight tester",
        "Fo data logger / thermal validation system used during PQ (NIST traceable reference)",
        "Safety relief valve: set pressure and reseat pressure — annual bench test",
        "Timer/clock: accuracy ±30 seconds over 1 hour",
    ],
    safety_checks=[
        "Pressure vessel statutory inspection (annual / biennial per PSSR 2000 or local code)",
        "Door interlock: door cannot open when chamber pressure > 0.1 bar — verified every cycle",
        "Safety relief valve: test annually with calibrated gauge, replace if set pressure drifts",
        "Steam supply isolation valve labelled and accessible for emergency shutdown",
        "Burn risk labelling on chamber exterior and door handles",
        "Operator PPE: heat-resistant gloves, safety goggles when unloading",
        "No flammable or pressurised aerosol items in autoclave",
    ],
    documentation_checklist=[
        "Pressure vessel design registration and ASME / PED certificate",
        "Steam supply quality test report (dryness, non-condensable gas, superheat)",
        "Temperature sensor calibration certificates (NIST traceable, all RTDs/TCs)",
        "Pressure transducer calibration certificate",
        "Safety relief valve bench test certificate (annual)",
        "PQ heat distribution and heat penetration study reports",
        "Biological Indicator study report",
        "PLC cycle configuration records and change control documents",
        "Batch records / cycle printouts (retained per retention SOP)",
        "Preventive Maintenance SOP and completed PM records",
        "Operator training records (including safety and emergency procedures)",
        "Instrument logbook (calibration, PM, deviations, cycle failures)",
    ],
    standard_acceptance_criteria=[
        "Temperature uniformity (empty): all sensors within ±1.0°C of set point",
        "Heat penetration: Fo ≥ 12 min at coldest point in product load",
        "Biological Indicator: 0/0 growth in all BI units after cycle",
        "Vacuum leak rate: ≤ 1.3 mbar/min (porous load sterilizers)",
        "Bowie-Dick test: uniform colour change across test pack",
        "Cycle reproducibility: ≥ 3 consecutive passing cycles",
        "Door interlock: 100% prevention of opening under pressure",
        "Batch record: all mandatory fields complete and legible",
    ],
    common_deviations=[
        "Temperature non-uniformity due to blocked steam diffuser — inspect and clean regularly",
        "Air pocket/cold spot at drain end — verify air removal system and drain TC location",
        "Door gasket leakage during cycle — inspect gasket condition before every use",
        "Cycle abort due to steam pressure fluctuation — check steam supply pressure regulator",
        "Batch record incomplete / printer jam — verify printer paper and ink before cycle",
        "BI positive result — full investigation required: cycle parameters, load, BI storage",
        "Fo value below minimum — increase cycle time or investigate temperature sensor drift",
    ],
))


# ─── VHP Generator ────────────────────────────────────────────────────────────

_register(EquipmentProfile(
    name="VHP GENERATOR",
    aliases=["vhp", "vapourised hydrogen peroxide", "vaporised hydrogen peroxide",
             "vhp sterilizer", "vhp decontamination system", "hydrogen peroxide vapour",
             "biodecontamination unit", "pass-through vhp"],
    description=(
        "A Vapourised Hydrogen Peroxide (VHP) Generator produces and delivers H₂O₂ vapour "
        "for surface decontamination and sterilization of isolators, pass-through chambers, "
        "cleanrooms, and equipment surfaces. Operates through four phases: dehumidification, "
        "conditioning, decontamination (hold), and aeration (catalytic decomposition to H₂O + O₂). "
        "Critical for sterile manufacturing per EU GMP Annex 1."
    ),
    applicable_regulations=[
        "EU GMP Annex 1 — Manufacture of Sterile Medicinal Products (2022), section 4.27",
        "ISO 14937 — Sterilization of health-care products: Gaseous sterilizing agents",
        "ISO 22441 — Low temperature sterilization — VHP",
        "EN 17126 — Sterilization of medical devices (VHP)",
        "21 CFR Part 211.113 — Microbiological contamination control",
        "ISPE Baseline Guide Vol. 5 — Commissioning and Qualification",
        "PDA Technical Report 61 — Steam-in-Place (includes vapour phase sterilants)",
        "OSHA 29 CFR 1910.1000 — Workplace H₂O₂ exposure limits (1 ppm TWA, 75 ppm STEL)",
    ],
    required_utilities=[
        "H₂O₂ supply: 30–35% pharmaceutical-grade H₂O₂ solution, UN3149 storage and handling",
        "Compressed air: clean, dry, oil-free, 6 bar for vaporiser and valve actuation",
        "Electrical: 220–240 V AC, 50 Hz, 15 A dedicated circuit",
        "Exhaust/aeration: HEPA-filtered exhaust or catalytic converter (decompose H₂O₂ to H₂O + O₂)",
        "Ambient temperature: 15–25°C for efficient vaporisation",
        "Interlocked enclosure / isolator with sealed entry points",
    ],
    critical_components=[
        "H₂O₂ vaporiser (flash evaporation or heated carrier gas injection)",
        "H₂O₂ concentration sensor (electrochemical or NIR, ppm range)",
        "Residual H₂O₂ sensor for aeration end-point determination (≤ 1 ppm)",
        "Relative humidity sensor (% RH — critical for condensation control)",
        "Temperature sensors within enclosure",
        "HEPA filtration for carrier gas and exhaust streams",
        "Catalytic converter / activated carbon for H₂O₂ decomposition during aeration",
        "Mass flow controller for H₂O₂ delivery rate",
        "PLC / SCADA with batch record generation and 21 CFR Part 11 audit trail",
        "Biological Indicator test carriers (for cycle validation)",
    ],
    iq_checklist=[
        "Verify VHP generator model, serial number, H₂O₂ vaporiser capacity against URS/PO",
        "Confirm H₂O₂ concentration sensor range, resolution, and last factory calibration date",
        "Verify RH sensor installation, range (0–100% RH), and calibration",
        "Check HEPA filter installation: integrity test certificate and DOP/PAO challenge results",
        "Confirm catalytic converter / exhaust catalyst installation and certification",
        "Verify PLC software version, cycle program parameters, and audit trail activation",
        "Check H₂O₂ supply connections: compatible materials (SS 316L, PTFE), no copper or PVC",
        "Verify room/enclosure interlocking: VHP cannot run if door is open; doors seal during cycle",
        "Confirm personal H₂O₂ monitor (electrochemical sensor) available and calibrated",
        "Check all temperature sensor positions and calibration certificates",
        "Verify emergency stop and H₂O₂ leak alarm system (alarm at ≥ 1 ppm in operator area)",
        "Confirm equipment registration in asset management system",
        "Verify H₂O₂ storage: labelled, ventilated, away from combustibles, secondary containment",
    ],
    oq_tests=[
        "Dehumidification phase: RH reduction from ambient to < 30% RH within specified time",
        "H₂O₂ concentration profile: conditioning phase ramp-up to target ppm (e.g., 250–500 ppm)",
        "Hold phase concentration stability: H₂O₂ maintained ±20% of target over hold time",
        "Temperature distribution during cycle: all sensor locations within ±2°C",
        "Aeration phase: H₂O₂ concentration decreases to ≤ 1 ppm within specified time",
        "Cycle repeatability: 3 consecutive cycles, H₂O₂ concentration profile RSD ≤ 10%",
        "Door interlock: attempt to open door during active VHP phase — must be prevented",
        "H₂O₂ alarm test: simulate sensor reading of 2 ppm in operator area — alarm must trigger",
        "Audit trail verification: all cycle data (H₂O₂, RH, temp, timestamps) captured and locked",
        "Mass flow controller accuracy: delivered H₂O₂ volume matches set value ±5%",
    ],
    pq_tests=[
        "Biological Indicator study: Geobacillus stearothermophilus or Bacillus atrophaeus spores, 6-log reduction",
        "D-value determination at target concentration/temperature for BIs used",
        "Worst-case location study: BIs placed at critical hard-to-reach positions, all negative",
        "Cycle reproducibility: ≥ 3 consecutive successful BI challenges",
        "Material compatibility: confirm no adverse effects on materials exposed to VHP cycle",
        "Residual H₂O₂ measurement post-aeration: ≤ 1 ppm at all sensor points before re-entry",
        "Environmental monitoring: surface agar plates post-cycle meet cleanroom specification",
    ],
    calibration_points=[
        "H₂O₂ concentration sensor: 0, 100, 250, 500 ppm — certified reference gas or wet chemistry",
        "Residual H₂O₂ sensor: 0, 0.5, 1.0, 2.0 ppm — for aeration end-point accuracy",
        "RH sensor: 11, 33, 75% RH — saturated salt solution references",
        "Temperature sensors: 15°C, 25°C, 35°C — NIST-traceable reference",
        "Mass flow controller: 0.5, 1.0, 2.0 g/min H₂O₂ delivery",
        "Personal H₂O₂ monitor worn by operator: 0.5, 1.0 ppm",
    ],
    safety_checks=[
        "H₂O₂ leak alarm (≥ 1 ppm in operator area): tested at each qualification event",
        "Emergency shutdown: immediate cycle abort and forced aeration on activation",
        "Interlocked door: cannot be opened during active VHP phase",
        "Personal H₂O₂ monitor: mandatory for all operators entering VHP-treated area",
        "PPE: chemical splash goggles, nitrile gloves, chemical-resistant apron when handling H₂O₂",
        "H₂O₂ storage: vented, cool, away from reducing agents and combustibles",
        "OSHA exposure limit: TWA 1 ppm, STEL 75 ppm — ambient monitoring programme",
        "Eyewash station within 10 seconds of H₂O₂ handling area",
        "Spill kit for H₂O₂: sodium thiosulfate neutralisation agent available",
    ],
    documentation_checklist=[
        "Vendor IQ/OQ package and factory acceptance test report",
        "H₂O₂ sensor calibration certificates",
        "HEPA filter integrity test certificates",
        "Catalytic converter performance certificate",
        "PLC cycle validation and audit trail configuration document",
        "Biological Indicator study reports (PQ)",
        "Material compatibility study reports",
        "H₂O₂ SDS and storage compliance records",
        "Operator training records (H₂O₂ safety and VHP operation)",
        "Cycle batch records (all H₂O₂, RH, temp data for each decontamination run)",
        "Instrument logbook (calibration, PM, deviations, sensor replacements)",
        "Preventive Maintenance SOP",
    ],
    standard_acceptance_criteria=[
        "Dehumidification: RH < 30% before H₂O₂ injection",
        "Hold phase H₂O₂: within ±20% of target concentration throughout hold",
        "Aeration end-point: residual H₂O₂ ≤ 1 ppm at all sensor locations",
        "Biological Indicator: 6-log reduction (0/0 positives at all worst-case locations)",
        "Cycle reproducibility: ≥ 3 consecutive passing cycles with BI confirmation",
        "H₂O₂ alarm: triggers at ≤ 1 ppm in operator area",
        "Temperature uniformity: ±2°C across all sensor positions",
    ],
    common_deviations=[
        "Condensate formation on surfaces due to RH > 30% before injection — extend dehumidification",
        "H₂O₂ concentration lower than target due to supply bottle depletion or vaporiser scaling",
        "Aeration time exceeding limit due to catalytic converter saturation — replace converter",
        "BI positive result at a specific location — investigate for shadowing, condensate, or cycle abort",
        "Personal H₂O₂ monitor not calibrated or battery dead before entry",
        "Material discolouration or degradation post-cycle — material compatibility study required",
        "Audit trail gaps due to PLC power interruption — UPS installation recommended",
    ],
))
